/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TestPanel.java
 *
 * Created on 5-dec-2008, 14:23:15
 */

package eu.scy.elobrowser.model.mapping.editor;

import javax.swing.JButton;
import javax.swing.JLabel;
import org.jdesktop.layout.GroupLayout;
import org.jdesktop.layout.LayoutStyle;

/**
 *
 * @author sikkenj
 */
public class TestPanel extends javax.swing.JPanel {

    /** Creates new form TestPanel */
    public TestPanel() {
        initComponents();
		  GroupLayout grouplayout;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jLabel1 = new JLabel();
      jButton1 = new JButton();

      jLabel1.setText("jLabel1");

      jButton1.setText("jButton1");

      GroupLayout layout = new GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(GroupLayout.LEADING)
         .add(layout.createSequentialGroup()
            .addContainerGap()
            .add(jLabel1)
            .addContainerGap(356, Short.MAX_VALUE))
         .add(GroupLayout.TRAILING, layout.createSequentialGroup()
            .addContainerGap(315, Short.MAX_VALUE)
            .add(jButton1)
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(GroupLayout.LEADING)
         .add(layout.createSequentialGroup()
            .addContainerGap()
            .add(jLabel1)
            .addPreferredGap(LayoutStyle.RELATED, 241, Short.MAX_VALUE)
            .add(jButton1)
            .addContainerGap())
      );
   }// </editor-fold>//GEN-END:initComponents


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private JButton jButton1;
   private JLabel jLabel1;
   // End of variables declaration//GEN-END:variables

}
