// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package eu.scy.mobile.toolbroker.demo.client;


public class MobileELO {
    protected java.lang.String b64Image;
    protected java.lang.String description;
    protected java.lang.String title;
    
    public MobileELO() {
    }
    
    public MobileELO(java.lang.String b64Image, java.lang.String description, java.lang.String title) {
        this.b64Image = b64Image;
        this.description = description;
        this.title = title;
    }
    
    public java.lang.String getB64Image() {
        return b64Image;
    }
    
    public void setB64Image(String b64Image) {
        this.b64Image = b64Image;
    }
    
    public java.lang.String getDescription() {
        return description;
    }
    
    public void setDescription(java.lang.String description) {
        this.description = description;
    }
    
    public java.lang.String getTitle() {
        return title;
    }
    
    public void setTitle(java.lang.String title) {
        this.title = title;
    }
}
