// This class was generated by 172 StubGenerator.
// Contents subject to change without notice.
// @generated

package eu.scy.mobile.toolbroker.demo.client;

import javax.xml.rpc.JAXRPCException;
import javax.xml.namespace.QName;
import javax.microedition.xml.rpc.Operation;
import javax.microedition.xml.rpc.Type;
import javax.microedition.xml.rpc.ComplexType;
import javax.microedition.xml.rpc.Element;

public class RepositoryService_Stub implements RepositoryService, javax.xml.rpc.Stub {
	private String[] _propertyNames;
	private Object[] _propertyValues;

	public RepositoryService_Stub() {
		_propertyNames = new String[] {ENDPOINT_ADDRESS_PROPERTY};
		_propertyValues = new Object[] {"http://localhost:8080/scy-useradmin-web/services/RepositoryService"};
	}

	public void _setProperty(String name, Object value) {
		int size = _propertyNames.length;
		for (int i = 0; i < size; ++i) {
			if (_propertyNames[i].equals(name)) {
				_propertyValues[i] = value;
				return;
			}
		}
		// Need to expand our array for a new property
		String[] newPropNames = new String[size + 1];
		System.arraycopy(_propertyNames, 0, newPropNames, 0, size);
		_propertyNames = newPropNames;
		Object[] newPropValues = new Object[size + 1];
		System.arraycopy(_propertyValues, 0, newPropValues, 0, size);
		_propertyValues = newPropValues;

		_propertyNames[size] = name;
		_propertyValues[size] = value;
	}

	public Object _getProperty(String name) {
		for (int i = 0; i < _propertyNames.length; ++i) {
			if (_propertyNames[i].equals(name)) {
				return _propertyValues[i];
			}
		}
		if (ENDPOINT_ADDRESS_PROPERTY.equals(name) || USERNAME_PROPERTY.equals(name) || PASSWORD_PROPERTY.equals(name)) {
			return null;
		}
		if (SESSION_MAINTAIN_PROPERTY.equals(name)) {
			return new java.lang.Boolean(false);
		}
		throw new JAXRPCException("Stub does not recognize property: "+name);
	}

	protected void _prepOperation(Operation op) {
		for (int i = 0; i < _propertyNames.length; ++i) {
			op.setProperty(_propertyNames[i], _propertyValues[i].toString());
		}
	}

	// 
	//  Begin user methods
	// 

	public java.lang.String saveELO(MobileELO arg0) throws java.rmi.RemoteException {
		// Copy the incoming values into an Object array if needed.
		Object[] inputObject = new Object[1];
		Object[] mobileELOObject;
		if (arg0 == null) {
			mobileELOObject = null;
		} else {
			mobileELOObject = new Object[3];
			mobileELOObject[0] = arg0.getB64Image();
			mobileELOObject[1] = arg0.getDescription();
			mobileELOObject[2] = arg0.getTitle();
		}
		inputObject[0] = mobileELOObject;

		Operation op = Operation.newInstance(_qname_saveELO, _type_saveELO, _type_saveELOResponse);
		_prepOperation(op);
		op.setProperty(Operation.SOAPACTION_URI_PROPERTY, "");
		Object resultObj;
		try {
			resultObj = op.invoke(inputObject);
		} catch (JAXRPCException e) {
			Throwable cause = e.getLinkedCause();
			if (cause instanceof java.rmi.RemoteException) {
				throw (java.rmi.RemoteException) cause;
			}
			throw e;
		}
		java.lang.String result;
		// Convert the result into the right Java type.
		// Unwrapped return value
		Object _returnObj = ((Object[])resultObj)[0];
		result = (java.lang.String)_returnObj;
		return result;
	}

	public MobileELO getELO(int arg0) throws java.rmi.RemoteException {
		// Copy the incoming values into an Object array if needed.
		Object[] inputObject = new Object[1];
		inputObject[0] = new java.lang.Integer(arg0);

		Operation op = Operation.newInstance(_qname_getELO, _type_getELO, _type_getELOResponse);
		_prepOperation(op);
		op.setProperty(Operation.SOAPACTION_URI_PROPERTY, "");
		Object resultObj;
		try {
			resultObj = op.invoke(inputObject);
		} catch (JAXRPCException e) {
			Throwable cause = e.getLinkedCause();
			if (cause instanceof java.rmi.RemoteException) {
				throw (java.rmi.RemoteException) cause;
			}
			throw e;
		}
		eu.scy.mobile.toolbroker.demo.client.MobileELO result;
		// Convert the result into the right Java type.
		// Unwrapped return value
		Object[] _returnObj = (Object[]) ((Object[])resultObj)[0];
		if (_returnObj == null) {
			result = null;
		} else {
			result = new eu.scy.mobile.toolbroker.demo.client.MobileELO();
			java.lang.String string;
			Object b64ImageObj = _returnObj[0];
			string = (java.lang.String)b64ImageObj;
			result.setB64Image(string);
			java.lang.String string2;
			Object descriptionObj = _returnObj[1];
			string2 = (java.lang.String)descriptionObj;
			result.setDescription(string2);
			java.lang.String string3;
			Object titleObj = _returnObj[2];
			string3 = (java.lang.String)titleObj;
			result.setTitle(string3);
		}
		return result;
	}
	// 
	//  End user methods
	// 

	protected static final QName _qname_arg0 = new QName("", "arg0");
	protected static final QName _qname_b64Image = new QName("", "b64Image");
	protected static final QName _qname_description = new QName("", "description");
	protected static final QName _qname_return = new QName("", "return");
	protected static final QName _qname_title = new QName("", "title");
	protected static final QName _qname_getELO = new QName("http://mobileservice.webservices.scy.eu/", "getELO");
	protected static final QName _qname_getELOResponse = new QName("http://mobileservice.webservices.scy.eu/", "getELOResponse");
	protected static final QName _qname_saveELO = new QName("http://mobileservice.webservices.scy.eu/", "saveELO");
	protected static final QName _qname_saveELOResponse = new QName("http://mobileservice.webservices.scy.eu/", "saveELOResponse");
	protected static final Element _type_saveELO;
	protected static final Element _type_saveELOResponse;
	protected static final Element _type_getELO;
	protected static final Element _type_getELOResponse;
	static {
		// Create all of the Type's that this stub uses, once.
		Element _type_b64Image;
		_type_b64Image = new Element(_qname_b64Image, Type.STRING, 0, 1, false);
		Element _type_description;
		_type_description = new Element(_qname_description, Type.STRING, 0, 1, false);
		Element _type_title;
		_type_title = new Element(_qname_title, Type.STRING, 0, 1, false);
		ComplexType _complexType_mobileELO;
		_complexType_mobileELO = new ComplexType();
		_complexType_mobileELO.elements = new Element[3];
		_complexType_mobileELO.elements[0] = _type_b64Image;
		_complexType_mobileELO.elements[1] = _type_description;
		_complexType_mobileELO.elements[2] = _type_title;
		Element _type_arg0;
		_type_arg0 = new Element(_qname_arg0, _complexType_mobileELO, 0, 1, false);
		ComplexType _complexType_saveELO;
		_complexType_saveELO = new ComplexType();
		_complexType_saveELO.elements = new Element[1];
		_complexType_saveELO.elements[0] = _type_arg0;
		_type_saveELO = new Element(_qname_saveELO, _complexType_saveELO);
		Element _type_return;
		_type_return = new Element(_qname_return, Type.STRING, 0, 1, false);
		ComplexType _complexType_saveELOResponse;
		_complexType_saveELOResponse = new ComplexType();
		_complexType_saveELOResponse.elements = new Element[1];
		_complexType_saveELOResponse.elements[0] = _type_return;
		_type_saveELOResponse = new Element(_qname_saveELOResponse, _complexType_saveELOResponse);
		Element _type_arg02;
		_type_arg02 = new Element(_qname_arg0, Type.INT);
		ComplexType _complexType_getELO;
		_complexType_getELO = new ComplexType();
		_complexType_getELO.elements = new Element[1];
		_complexType_getELO.elements[0] = _type_arg02;
		_type_getELO = new Element(_qname_getELO, _complexType_getELO);
		Element _type_return2;
		_type_return2 = new Element(_qname_return, _complexType_mobileELO, 0, 1, false);
		ComplexType _complexType_getELOResponse;
		_complexType_getELOResponse = new ComplexType();
		_complexType_getELOResponse.elements = new Element[1];
		_complexType_getELOResponse.elements[0] = _type_return2;
		_type_getELOResponse = new Element(_qname_getELOResponse, _complexType_getELOResponse);
	}

}
