// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package eu.scy.mobile.toolbroker.demo.client;


public class SaveELOResponse {
    protected java.lang.String _return;
    
    public SaveELOResponse() {
    }
    
    public SaveELOResponse(java.lang.String _return) {
        this._return = _return;
    }
    
    public java.lang.String get_return() {
        return _return;
    }
    
    public void set_return(java.lang.String _return) {
        this._return = _return;
    }
}
