// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package eu.scy.mobile.toolbroker.demo.client;


public class SaveELO {
    protected MobileELO arg0;
    
    public SaveELO() {
    }
    
    public SaveELO(MobileELO arg0) {
        this.arg0 = arg0;
    }
    
    public MobileELO getArg0() {
        return arg0;
    }
    
    public void setArg0(MobileELO arg0) {
        this.arg0 = arg0;
    }
}
