/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EloXmlViewer.java
 *
 * Created on 22-sep-2009, 18:06:16
 */

package eu.scy.client.desktop.scydesktop.tools.drawers.xmlviewer;

import java.net.URI;
import roolo.api.IRepository;
import roolo.elo.api.IELO;

/**
 *
 * @author sikkenj
 */
public class EloXmlViewer extends javax.swing.JPanel {

    /** Creates new form EloXmlViewer */
    public EloXmlViewer() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      updateButton = new javax.swing.JButton();
      xmlViewerScrollPane = new javax.swing.JScrollPane();
      xmlViewer = new javax.swing.JTextArea();

      updateButton.setText("Update");

      xmlViewer.setColumns(20);
      xmlViewer.setEditable(false);
      xmlViewer.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
      xmlViewer.setRows(5);
      xmlViewerScrollPane.setViewportView(xmlViewer);

      org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
         .add(updateButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
         .add(xmlViewerScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
         .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
            .add(xmlViewerScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(updateButton))
      );
   }// </editor-fold>//GEN-END:initComponents


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton updateButton;
   private javax.swing.JTextArea xmlViewer;
   private javax.swing.JScrollPane xmlViewerScrollPane;
   // End of variables declaration//GEN-END:variables
   private IRepository repository;
   private URI eloUri;

   public void setRepository(IRepository repository)
   {
      this.repository = repository;
   }

   public void setEloUri(URI eloUri)
   {
      this.eloUri = eloUri;
   }

   private void showXml()
   {
      String xml = "";
      if (repository == null)
      {
         xml = "Repository is not defined";
      }
      else if (eloUri == null)
      {
         xml = "ELO uri is not defined";
      }
      else
      {
         IELO elo = repository.retrieveELO(eloUri);
         if (elo == null)
         {
            xml = "ELO does not exists.\n\nURI: " + eloUri.toString();
         }
         else
         {
            xml = elo.getXml();
         }
      }
      xmlViewer.setText(xml);
   }

}
