/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package eu.scy.client.tools.fxflyingsaucer;

/**
 *
 * @author sikken
 */
public class TestFlyingSaucerPanel extends javax.swing.JFrame
{

   /** Creates new form BrowserTestFrame */
   public TestFlyingSaucerPanel()
   {
      initComponents();
   }

   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   private void initComponents()
   {
      setTitle("Flying Saucer test window");
      FlyingSaucerPanel browser = new FlyingSaucerPanel(true);

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(browser, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE));
      layout.setVerticalGroup(
         layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(browser, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE));

      pack();
   }

   /**
    * @param args the command line arguments
    */
   public static void main(String args[])
   {
      java.awt.EventQueue.invokeLater(new Runnable()
      {

         public void run()
         {
            new TestFlyingSaucerPanel().setVisible(true);
         }
      });
   }
}
