/*  $Id$
 *  
 *  File	autoload.pl
 *  Part of	IC - educational data mining
 *  Author	Anjo Anjewierden, a.a.anjewierden@utwente.nl
 *  Purpose	Auto loading of PCE classes
 *  Works with	SWI-Prolog (www.swi-prolog.org)
 *  
 *  Notice	Copyright (c) 2007, 2008, 2009, 2010  University of Twente
 *  
 *  History	08/02/07  (Created)
 *  		06/12/10  (Last modified)
 */ 

/*------------------------------------------------------------
 *  Directives
 *------------------------------------------------------------*/

:- module(autoload_ic,
	  []).

:- use_module(load).

:- use_module(library(pce)).


/*------------------------------------------------------------
 *  Autoload (see also grep -H of pce_begin_class at the end)
 *------------------------------------------------------------*/

:- pce_autoload(drag_and_drop_gesture,		library(dragdrop)).
:- pce_autoload(finder,				library(find_file)).
:- pce_autoload(float_item,			library(pce_float_item)).
:- pce_autoload(report_dialog,			library(pce_report)).
:- pce_autoload(tabbed_window,			library(tabbed_window)).

:- pce_autoload(select_directory,	utilities(select_directory)).
:- pce_autoload(bounding_box,			utilities(pce_bounding_box)).
:- pce_autoload(diabolo,                	utilities(pce_diabolo)).
:- pce_autoload(gradient_browser,		utilities(pce_gradient)).
:- pce_autoload(gradient_colour,		utilities(pce_gradient)).
:- pce_autoload(gradient_hsv_colour,		utilities(pce_gradient)).
:- pce_autoload(gradient_hsv_image,		utilities(pce_gradient)).

:- pce_autoload(action_type_overview,    	ic(pce_action_type)).
:- pce_autoload(action_type_symbol_base, 	ic(pce_action_type)).
:- pce_autoload(annotation_single,       	ic(pce_annotation)).
:- pce_autoload(annotation_type_symbol,  	ic(pce_symbol)).
:- pce_autoload(ic_configuration,		ic(configuration)).
:- pce_autoload(ic_convert_menu,		ic(tool_ic)).
:- pce_autoload(ic_file_menu,			ic(tool_ic)).
:- pce_autoload(ic_help_menu,			ic(tool_ic)).
:- pce_autoload(ic_menu_bar,			ic(tool_ic)).
:- pce_autoload(ic_special_menu,		ic(tool_ic)).
:- pce_autoload(ic_tool,			ic(tool_ic)).
:- pce_autoload(ic_tool_class,			ic(configuration)).
:- pce_autoload(ic_tools_menu,			ic(tool_ic)).

:- pce_autoload(sdm_auxiliary,			sdm(pce_sdm_model)).
:- pce_autoload(sdm_base,			sdm(pce_sdm_model)).
:- pce_autoload(sdm_constant,			sdm(pce_sdm_model)).
:- pce_autoload(sdm_dataset,			sdm(pce_sdm_model)).
:- pce_autoload(sdm_figure,			sdm(pce_sdm_model)).
:- pce_autoload(sdm_flow,	        	sdm(pce_sdm_model)).
:- pce_autoload(sdm_inquiry_sequence,		sdm(pce_sdm_model)).
:- pce_autoload(sdm_relation,			sdm(pce_sdm_model)).
:- pce_autoload(sdm_sequence,			sdm(pce_sdm_model)).
:- pce_autoload(sdm_stock,			sdm(pce_sdm_model)).
:- pce_autoload(sdm_window,			sdm(pce_sdm_model)).
:- pce_autoload(sequence_controller,    	sdm(pce_sdm_model)).

:- pce_autoload(assignment_browser,		win(assignment_browser)).
:- pce_autoload(cmap_browser,		        win(cmap_browser)).
:- pce_autoload(edge_label_browser,		win(gls_term_browser)).
:- pce_autoload(experiment_browser,		win(experiment_browser)).
:- pce_autoload(experiment_dialog,		win(experiment_dialog)).
:- pce_autoload(gls_browser,			win(gls_browser)).
:- pce_autoload(ic_canvas,			win(ic_canvas)).
:- pce_autoload(ic_tabbed_window,		win(tabbed_window)).
:- pce_autoload(ic_window_tab,			win(tabbed_window)).
:- pce_autoload(learner_browser,		win(learner_browser)).
:- pce_autoload(model_browser,		        win(model_browser)).
:- pce_autoload(node_label_browser,		win(gls_term_browser)).
:- pce_autoload(node_term_browser,		win(gls_term_browser)).
:- pce_autoload(session_browser,		win(session_browser)).
:- pce_autoload(session_browser,		win(session_browser)).
:- pce_autoload(session_select_tool,    	win(session_select)).
:- pce_autoload(simulation_browser,		win(simulation_browser)).
:- pce_autoload(specify_concept_set_dialog,	win(specify_concept_set)).
:- pce_autoload(specify_concept_set_tool,	win(specify_concept_set)).

:- pce_autoload(gradient_matrix, 		pce(gradient_matrix)).
:- pce_autoload(gradient_matrix_cell, 		pce(gradient_matrix)).
:- pce_autoload(gradient_matrix_empty_cell, 	pce(gradient_matrix)).

:- pce_autoload(bounded_figure,			mod(pce_window_layout)).
:- pce_autoload(change_specification_detail,	mod(gr_action_detail)).
:- pce_autoload(inquiry_global,			mod(pce_inquiry_global)).
:- pce_autoload(inquiry_global_overview,	mod(pce_inquiry_global)).
:- pce_autoload(inquiry_global_session, 	mod(pce_inquiry_global)).
:- pce_autoload(mod_canvas,			mod(tool_mod)).
:- pce_autoload(mod_edit_menu,			mod(tool_mod)).
:- pce_autoload(mod_file_menu,			mod(tool_mod)).
:- pce_autoload(mod_menu_bar,			mod(tool_mod)).
:- pce_autoload(mod_specifications_menu,	mod(tool_mod)).
:- pce_autoload(mod_tool,			mod(tool_mod)).
:- pce_autoload(mod_view_menu,			mod(tool_mod)).
:- pce_autoload(model_elements,			mod(tool_mod)).
:- pce_autoload(window_box,			mod(pce_window_layout)).
:- pce_autoload(window_in_focus,		mod(pce_window_layout)).
:- pce_autoload(window_in_focus,        	mod(pce_window_layout)).
:- pce_autoload(window_layout,			mod(pce_window_layout)).
:- pce_autoload(window_layout,          	mod(pce_window_layout)).
:- pce_autoload(window_layout_sequence,		mod(pce_window_layout)).
:- pce_autoload(window_layout_sequence, 	mod(pce_window_layout)).

:- pce_autoload(action_base,		 	seq(pce_action_sequence)).
:- pce_autoload(action_seqset_list,      	seq(pce_action_sequence)).
:- pce_autoload(action_sequence,         	seq(pce_action_sequence)).
:- pce_autoload(action_type_sequence_list, 	seq(pce_action_sequence)).
:- pce_autoload(item_sequence_style_popup,	seq(item_sequence_style)).
:- pce_autoload(seq_process_window,		seq(process_window)).
:- pce_autoload(seq_tool,			seq(tool_seq)).
:- pce_autoload(sequence_select_gesture,	seq(pce_sequence_select_gesture)).
:- pce_autoload(session_action_sequence, 	seq(pce_action_sequence)).

:- pce_autoload(cmap_figure,			cmap(pce_cmap)).
:- pce_autoload(cmap_node,			cmap(pce_cmap)).
:- pce_autoload(cmap_link,			cmap(pce_cmap)).

:- pce_autoload(gaze_tool,	        	gaze_tracker(tool_gaze)).
:- pce_autoload(look_zone_path,			gaze_tracker(pce_look_zone_path)).

:- pce_autoload(gls_tool,			gls(tool_gls)).

:- pce_autoload(element_evaluation_timeline_overview,	edm(gr_items_over_time)).
:- pce_autoload(inspect_values,			edm(gr_votat)).
:- pce_autoload(model_evaluation_bar_chart,	edm(gr_element_evaluation)).
:- pce_autoload(model_evaluation_bar_chart,	edm(gr_model_evaluation_bar_chart)).
:- pce_autoload(model_quality,			edm(gr_votat)).
:- pce_autoload(phase,				edm(gr_phase)).
:- pce_autoload(simulation_behaviour_base,	edm(gr_votat)).
:- pce_autoload(simulation_behaviour_overview,	edm(simulation)).
:- pce_autoload(votat,				edm(gr_votat)).

:- pce_autoload(coded_chat,			coding(coded_chat)).
:- pce_autoload(coding,				coding(coded_chat)).
:- pce_autoload(coding_strips,			coding(coding_strip)).
:- pce_autoload(episode_chat_figure,    	coding(episode_chat)).
:- pce_autoload(episode_type_figure,    	coding(episode_type)).
:- pce_autoload(seq_coding_window,		coding(seq_coding_window)).

:- pce_autoload(brick_conditions_menu,		brick(tool_brick)).
:- pce_autoload(brick_data_menu,		brick(tool_brick)).
:- pce_autoload(brick_decorator,		brick(decorator)).
:- pce_autoload(brick_decorator_index,		brick(decorator)).
:- pce_autoload(brick_dialog,			brick(tool_brick)).
:- pce_autoload(brick_edit_menu,		brick(tool_brick)).
:- pce_autoload(brick_end,			brick(brick)).
:- pce_autoload(brick_file_menu,		brick(tool_brick)).
:- pce_autoload(brick_index,			brick(brick)).
:- pce_autoload(brick_kleene_star,		brick(brick)).
:- pce_autoload(brick_menu_bar,			brick(tool_brick)).
:- pce_autoload(brick_mine_patterns,		brick(brick)).
:- pce_autoload(brick_preferences_dialog,	brick(win_preferences)).
:- pce_autoload(brick_preferences_tool,		brick(win_preferences)).
:- pce_autoload(brick_search_box,   		brick(search_box)).
:- pce_autoload(brick_start,			brick(brick)).
:- pce_autoload(brick_token2,			brick(brick)).
:- pce_autoload(brick_token2_sequence,		brick(brick)).
:- pce_autoload(brick_token2_sequences,		brick(brick)).
:- pce_autoload(brick_token2_sequences_by_condition, brick(brick)).
:- pce_autoload(brick_tool,			brick(tool_brick)).
:- pce_autoload(brick_view_menu,		brick(tool_brick)).
:- pce_autoload(brick_wildcard,			brick(brick)).
:- pce_autoload(brick_window,			brick(tool_brick)).
:- pce_autoload(wall_token2_sequences,		brick(wall)).

:- pce_autoload(native_matrix_table,		methods(pce_native_matrix_table)).

end_of_file.

./edm/animate_model_development.pl::- pce_begin_class(animate_model_development, frame).
./edm/animate_model_development.pl::- pce_begin_class(animate_model_development_canvas, picture).
./edm/animate_model_development.pl::- pce_begin_class(animate_model_development_dialog, dialog).
./edm/gr_votat.pl::- pce_begin_class(simulation_behaviour_base, figure).
./edm/gr_votat.pl::- pce_begin_class(votat, simulation_behaviour_base).
./edm/gr_votat.pl::- pce_begin_class(inspect_values, simulation_behaviour_base).
./edm/gr_votat.pl::- pce_begin_class(model_quality, simulation_behaviour_base).
./edm/gr_items_over_time.pl::- pce_begin_class(element_evaluation_timeline_overview, figure).
./edm/gr_items_over_time.pl::- pce_begin_class(items_over_time, figure).
./edm/gr_items_over_time.pl::- pce_begin_class(simple_tick, line).
./edm/gr_items_over_time.pl::- pce_begin_class(item_states_over_time, figure).
./edm/gr_items_over_time.pl::- pce_begin_class(element_evaluation, figure).
./edm/gr_items_over_time.pl::- pce_begin_class(relation_evaluation, figure).
./edm/simulation.pl::- pce_begin_class(simulation_behaviour_overview, figure).
./edm/gr_phase.pl::- pce_begin_class(phase, figure).
./edm/gr_model_evaluation_bar_chart.pl::- pce_begin_class(model_evaluation_bar_chart, figure).
./edm/model_runs/pce_model_runs.pl::- pce_begin_class(model_runs_link_time_figure, figure).
./edm/gr_element_evaluation.pl::- pce_begin_class(model_evaluation_bar_chart, figure).
./mod/gr_action_detail.pl::- pce_begin_class(change_specification_detail, action_detail).
./mod/pce_inquiry_global.pl::- pce_begin_class(inquiry_global_overview, figure).
./mod/pce_inquiry_global.pl::- pce_begin_class(inquiry_global_session, figure).
./mod/pce_inquiry_global.pl::- pce_begin_class(inquiry_global, figure).
./mod/pce_window_layout.pl::- pce_begin_class(bounded_figure, figure).
./mod/pce_window_layout.pl::- pce_begin_class(window_layout_sequence, figure).
./mod/pce_window_layout.pl::- pce_begin_class(window_layout, bounded_figure).
./mod/pce_window_layout.pl::- pce_begin_class(window_in_focus, bounded_figure).
./mod/pce_window_layout.pl::- pce_begin_class(window_box, box).
./mod/tool_mod.pl::- pce_begin_class(mod_tool, ic_tool_class).
./mod/tool_mod.pl::- pce_begin_class(mod_menu_bar, dialog).
./mod/tool_mod.pl::- pce_begin_class(mod_file_menu, popup).
./mod/tool_mod.pl::- pce_begin_class(mod_edit_menu, popup).
./mod/tool_mod.pl::- pce_begin_class(mod_view_menu, popup).
./mod/tool_mod.pl::- pce_begin_class(mod_specifications_menu, popup).
./mod/tool_mod.pl::- pce_begin_class(mod_canvas, picture).
./mod/tool_mod.pl::- pce_begin_class(model_elements, mod_canvas).
./pce/gradient_matrix.pl::- pce_begin_class(gradient_matrix, figure).
./pce/gradient_matrix.pl::- pce_begin_class(gradient_matrix_cell, box).
./pce/gradient_matrix.pl::- pce_begin_class(gradient_matrix_empty_cell, box).
./pce/model_evaluation_rule_timeline.pl::- pce_begin_class(model_evaluation_rule_timeline, figure).
./seq/pce_action_sequence.pl::- pce_begin_class(action_type_sequence_list, device).
./seq/pce_action_sequence.pl::- pce_begin_class(action_type_sequence, device).
./seq/pce_action_sequence.pl::- pce_begin_class(action_seqset_list, device).
./seq/pce_action_sequence.pl::- pce_begin_class(action_sequence_list, action_seqset_list).
./seq/pce_action_sequence.pl::- pce_begin_class(action_sequence, figure).
./seq/pce_action_sequence.pl::- pce_begin_class(action_base, annotation_single).
./seq/process_window.pl::- pce_begin_class(seq_process_window, seq_canvas).
./seq/process_window.pl::- pce_begin_class(seqset_process, device).
./seq/process_window.pl::- pce_begin_class(seq_process, figure).
./seq/process_window.pl::- pce_begin_class(action_process_line, device).
./seq/process_window.pl::- pce_begin_class(chat_process_line, action_process_line).
./seq/process_window.pl::- pce_begin_class(simulation_process_line, action_process_line).
./seq/process_window.pl::- pce_begin_class(answer_process_line, action_process_line).
./seq/process_window.pl::- pce_begin_class(episode_box, box).
./seq/item_sequence_style.pl::- pce_begin_class(item_sequence_style_popup, popup).
./seq/pce_sequence_select_gesture.pl::- pce_begin_class(sequence_select_gesture, gesture).
./seq/tool_seq.pl::- pce_begin_class(seq_tool, ic_tool_class).
./seq/tool_seq.pl::- pce_begin_class(seq_canvas, picture).
./seq/tool_seq.pl::- pce_begin_class(seq_action_types, picture).
./seq/tool_seq.pl::- pce_begin_class(seq_menu_bar, dialog).
./seq/tool_seq.pl::- pce_begin_class(seq_file_menu, popup).
./seq/tool_seq.pl::- pce_begin_class(seq_edit_menu, popup).
./seq/tool_seq.pl::- pce_begin_class(seq_view_menu, popup).
./seq/tool_seq.pl::- pce_begin_class(seq_tools_menu, popup).
./seq/tool_seq.pl::- pce_begin_class(seq_experimental_menu, popup).
./win/experiment_dialog.pl::- pce_begin_class(experiment_dialog, dialog).
./win/experiment_dialog.pl::- pce_begin_class(exp_item, text_item).
./win/keep/simulation_browser.pl::- pce_begin_class(simulation_browser, browser).
./win/keep/session_select.pl::- pce_begin_class(session_select_tool, frame).
./win/keep/session_select.pl::- pce_begin_class(session_select_dialog, dialog).
./win/keep/assignment_browser.pl::- pce_begin_class(assignment_browser, browser).
./win/keep/cmap_browser.pl::- pce_begin_class(cmap_browser, browser).
./win/gls_browser.pl::- pce_begin_class(gls_browser, browser).
./win/specify_term_set.pl::- pce_begin_class(specify_term_set_tool, frame).
./win/specify_term_set.pl::- pce_begin_class(specify_term_set_dialog, dialog).
./win/gls_term_browser.pl::- pce_begin_class(gls_term_browser, browser).
./win/gls_term_browser.pl::- pce_begin_class(node_label_browser, gls_term_browser).
./win/gls_term_browser.pl::- pce_begin_class(node_term_browser, gls_term_browser).
./win/gls_term_browser.pl::- pce_begin_class(edge_label_browser, gls_term_browser).
./win/gls_term_browser.pl::- pce_begin_class(node_word_browser, gls_term_browser).
./win/learner_browser.pl::- pce_begin_class(learner_browser, browser).
./win/tabbed_window.pl::- pce_begin_class(ic_tabbed_window, tabbed_window).
./win/tabbed_window.pl::- pce_begin_class(ic_window_tab, window_tab).
./win/model_browser.pl::- pce_begin_class(model_browser, browser).
./win/session_browser.pl::- pce_begin_class(session_browser, browser).
./win/experiment_browser.pl::- pce_begin_class(experiment_browser, browser).
./win/specify_concept_set.pl::- pce_begin_class(specify_concept_set_tool, frame).
./win/specify_concept_set.pl::- pce_begin_class(specify_concept_set_dialog, dialog).
./win/ic_canvas.pl::- pce_begin_class(ic_canvas, picture).
./pce_symbol.pl::- pce_begin_class(annotation_type_symbol, figure).
./pce_symbol.pl::- pce_begin_class(symbol_plus, path).
./pce_symbol.pl::- pce_begin_class(symbol_minus, figure).
./pce_symbol.pl::- pce_begin_class(symbol_unknown, text).
./pce_symbol.pl::- pce_begin_class(symbol_square, box).
./pce_symbol.pl::- pce_begin_class(symbol_circle, circle).
./pce_symbol.pl::- pce_begin_class(symbol_triangle, triangle).
./pce_symbol.pl::- pce_begin_class(symbol_start, figure).
./pce_symbol.pl::- pce_begin_class(symbol_finish, figure).
./pce_symbol.pl::- pce_begin_class(symbol_donut, figure).
./pce_annotation.pl::- pce_begin_class(annotation_base, figure).
./pce_annotation.pl::- pce_begin_class(annotation_single, annotation_base).
./pce_annotation.pl::- pce_begin_class(annotation_sequence, annotation_base).
./pce_annotation.pl::- pce_begin_class(annotation_pattern, annotation_base).
./tool_ic.pl::- pce_begin_class(ic_tool, ic_tool_class).
./tool_ic.pl::- pce_begin_class(ic_menu_bar, dialog).
./tool_ic.pl::- pce_begin_class(ic_file_menu, popup).
./tool_ic.pl::- pce_begin_class(ic_tools_menu, popup).
./tool_ic.pl::- pce_begin_class(ic_help_menu, popup).
./brick/uu/mod_brick_sequence.pl::- pce_begin_class(mod_brick_sequence, figure).
./brick/uu/explore_result.pl::- pce_begin_class(seq_explore_result, figure).
./brick/keep/code.pl::- pce_begin_class(seq_explore_window, mod_canvas).
./brick/keep/code.pl::- pce_begin_class(seq_explore_result, figure).
./brick/keep/code.pl::- pce_begin_class(mod_brick_sequence, figure).
./brick/keep/code.pl::- pce_begin_class(mod_decorator, figure).
./brick/keep/code.pl::- pce_begin_class(mod_brick_pattern, device).
./brick/keep/code.pl::- pce_begin_class(mod_brick_any_sequence, mod_brick_pattern).
./brick/keep/code.pl::- pce_begin_class(mod_brick_user_defined, mod_brick_pattern).
./brick/keep/code.pl::- pce_begin_class(mod_pattern_define, figure).
./brick/keep/code.pl::- pce_begin_class(seq_explore_pattern, device).
./brick/keep/code.pl::- pce_begin_class(seq_explore_index, device).
./brick/keep/code.pl::- pce_begin_class(mod_decorator_index, device).
./brick/keep/explore_window.pl::- pce_begin_class(seq_explore_window, seq_canvas).
./brick/keep/explore_window.pl::- pce_begin_class(seq_explore_result, figure).
./brick/keep/explore_window.pl::- pce_begin_class(seq_episode_brick, device).
./brick/keep/explore_window.pl::- pce_begin_class(seq_explore_pattern, device).
./brick/keep/explore_window.pl::- pce_begin_class(seq_explore_index, device).
./brick/keep/mod_brick_pattern.pl::- pce_begin_class(mod_brick_pattern, device).
./brick/keep/mod_brick_pattern.pl::- pce_begin_class(mod_brick_any_sequence, mod_brick_pattern).
./brick/keep/mod_brick_pattern.pl::- pce_begin_class(mod_brick_user_defined, mod_brick_pattern).
./brick/decorator.pl::- pce_begin_class(brick_decorator_index, device).
./brick/decorator.pl::- pce_begin_class(brick_decorator, figure).
./brick/brick.pl::- pce_begin_class(brick_base, figure).
./brick/brick.pl::- pce_begin_class(brick_token2, brick_base).
./brick/brick.pl::- pce_begin_class(brick_wildcard, brick_token2).
./brick/brick.pl::- pce_begin_class(brick_meta, brick_base).
./brick/brick.pl::- pce_begin_class(brick_meta_or, brick_meta).
./brick/brick.pl::- pce_begin_class(brick_meta_star, brick_meta).
./brick/brick.pl::- pce_begin_class(brick_meta_optional, brick_meta).
./brick/brick.pl::- pce_begin_class(brick_meta_negate, brick_meta).
./brick/brick.pl::- pce_begin_class(brick_meta_one_or_more, brick_meta).
./brick/brick.pl::- pce_begin_class(brick_meta_two_or_more, brick_meta).
./brick/brick.pl::- pce_begin_class(brick_meta_open_bracket, brick_meta).
./brick/brick.pl::- pce_begin_class(brick_meta_close_bracket, brick_meta).
./brick/brick.pl::- pce_begin_class(brick_terminator, brick_token2).
./brick/brick.pl::- pce_begin_class(brick_start, brick_terminator).
./brick/brick.pl::- pce_begin_class(brick_end, brick_terminator).
./brick/brick.pl::- pce_begin_class(brick_kleene_star, brick_token2).
./brick/brick.pl::- pce_begin_class(brick_index, figure).
./brick/brick.pl::- pce_begin_class(brick_token2_sequence, figure).
./brick/brick.pl::- pce_begin_class(brick_pattern_sequence, figure).
./brick/brick.pl::- pce_begin_class(brick_token2_sequences_base, figure).
./brick/brick.pl::- pce_begin_class(brick_token2_sequences, brick_token2_sequences_base).
./brick/brick.pl::- pce_begin_class(brick_sequences_systematic, brick_token2_sequences_base).
./brick/brick.pl::- pce_begin_class(brick_mine_patterns, brick_token2_sequences_base).
./brick/brick.pl::- pce_begin_class(brick_token2_sequences_by_condition, brick_token2_sequences_base).
./brick/search_box.pl::- pce_begin_class(brick_search_box, figure).
./brick/search_box.pl::- pce_begin_class(brick_search_buttons, figure).
./brick/search_box.pl::- pce_begin_class(brick_search_button, figure).
./brick/search_box.pl::- pce_begin_class(brick_search_meta_index, figure).
./brick/tool_brick.pl::- pce_begin_class(brick_tool, frame).
./brick/tool_brick.pl::- pce_begin_class(brick_window, ic_canvas).
./brick/tool_brick.pl::- pce_begin_class(brick_menu_bar, dialog).
./brick/tool_brick.pl::- pce_begin_class(brick_file_menu, popup).
./brick/tool_brick.pl::- pce_begin_class(brick_edit_menu, popup).
./brick/tool_brick.pl::- pce_begin_class(brick_view_menu, popup).
./brick/tool_brick.pl::- pce_begin_class(brick_data_menu, popup).
./brick/tool_brick.pl::- pce_begin_class(brick_dialog, dialog).
./brick/tool_brick.pl::- pce_begin_class(brick_tseq_menu, menu).
./brick/tool_brick.pl::- pce_begin_class(brick_conditions_menu, menu).
./brick/tool_brick.pl::- pce_begin_class(brick_metric_menu, menu).
./brick/win_preferences.pl::- pce_begin_class(brick_preferences_tool, frame).
./brick/win_preferences.pl::- pce_begin_class(brick_preferences_dialog, dialog).
./brick/win_preferences.pl::- pce_begin_class(brick_preferences_metrics_menu, menu).
./brick/groenlo.pl::- pce_begin_class(groenlo_token2, brick_token2).
./brick/wall.pl::- pce_begin_class(wall_token2_sequences, figure).
./configuration.pl::- pce_begin_class(ic_configuration, object).
./configuration.pl::- pce_begin_class(ic_tool_class, frame).
./umuai/gr_umuai.pl::- pce_begin_class(sdm_as_label, text).
./umuai/gr_umuai.pl::- pce_begin_class(eval, figure).
./umuai/gr_umuai.pl::- pce_begin_class(umuai_figure, figure).
./umuai/gr_umuai.pl::- pce_begin_class(umuai_modification_device, device).
./umuai/gr_umuai.pl::- pce_begin_class(umuai_base, text).
./explore-2011-03-02/keep/code.pl::- pce_begin_class(seq_explore_window, mod_canvas).
./explore-2011-03-02/keep/code.pl::- pce_begin_class(seq_explore_result, figure).
./explore-2011-03-02/keep/code.pl::- pce_begin_class(mod_brick_sequence, figure).
./explore-2011-03-02/keep/code.pl::- pce_begin_class(mod_decorator, figure).
./explore-2011-03-02/keep/code.pl::- pce_begin_class(mod_brick_pattern, device).
./explore-2011-03-02/keep/code.pl::- pce_begin_class(mod_brick_any_sequence, mod_brick_pattern).
./explore-2011-03-02/keep/code.pl::- pce_begin_class(mod_brick_user_defined, mod_brick_pattern).
./explore-2011-03-02/keep/code.pl::- pce_begin_class(mod_pattern_define, figure).
./explore-2011-03-02/keep/code.pl::- pce_begin_class(seq_explore_pattern, device).
./explore-2011-03-02/keep/code.pl::- pce_begin_class(seq_explore_index, device).
./explore-2011-03-02/keep/code.pl::- pce_begin_class(mod_decorator_index, device).
./explore-2011-03-02/keep/explore_window.pl::- pce_begin_class(seq_explore_window, seq_canvas).
./explore-2011-03-02/keep/explore_window.pl::- pce_begin_class(seq_explore_result, figure).
./explore-2011-03-02/keep/explore_window.pl::- pce_begin_class(seq_episode_brick, device).
./explore-2011-03-02/keep/explore_window.pl::- pce_begin_class(seq_explore_pattern, device).
./explore-2011-03-02/keep/explore_window.pl::- pce_begin_class(seq_explore_index, device).
./explore-2011-03-02/keep/mod_brick_pattern.pl::- pce_begin_class(mod_brick_pattern, device).
./explore-2011-03-02/keep/mod_brick_pattern.pl::- pce_begin_class(mod_brick_any_sequence, mod_brick_pattern).
./explore-2011-03-02/keep/mod_brick_pattern.pl::- pce_begin_class(mod_brick_user_defined, mod_brick_pattern).
./explore-2011-03-02/mod_decorator_index.pl::- pce_begin_class(mod_decorator_index, device).
./explore-2011-03-02/brick.pl::- pce_begin_class(brick_token2, figure).
./explore-2011-03-02/brick.pl::- pce_begin_class(brick_wildcard, brick_token2).
./explore-2011-03-02/brick.pl::- pce_begin_class(brick_terminator, brick_token2).
./explore-2011-03-02/brick.pl::- pce_begin_class(brick_start, brick_terminator).
./explore-2011-03-02/brick.pl::- pce_begin_class(brick_end, brick_terminator).
./explore-2011-03-02/brick.pl::- pce_begin_class(brick_kleene_star, brick_token2).
./explore-2011-03-02/brick.pl::- pce_begin_class(brick_user_defined, brick_token).
./explore-2011-03-02/brick.pl::- pce_begin_class(brick_pattern_define, figure).
./explore-2011-03-02/brick.pl::- pce_begin_class(brick_index, figure).
./explore-2011-03-02/brick.pl::- pce_begin_class(brick_token2_sequence, figure).
./explore-2011-03-02/brick.pl::- pce_begin_class(brick_pattern_sequence, figure).
./explore-2011-03-02/brick.pl::- pce_begin_class(brick_token2_sequence_base, figure).
./explore-2011-03-02/brick.pl::- pce_begin_class(brick_token2_sequences, brick_token2_sequence_base).
./explore-2011-03-02/brick.pl::- pce_begin_class(brick_sequences_systematic, brick_token2_sequence_base).
./explore-2011-03-02/brick.pl::- pce_begin_class(brick_mine_patterns, brick_token2_sequence_base).
./explore-2011-03-02/brick.pl::- pce_begin_class(brick_token2_sequences_by_condition, brick_token2_sequence_base).
./explore-2011-03-02/mod_brick_sequence.pl::- pce_begin_class(mod_brick_sequence, figure).
./explore-2011-03-02/search_box.pl::- pce_begin_class(brick_search_box, figure).
./explore-2011-03-02/search_box.pl::- pce_begin_class(brick_search_buttons, figure).
./explore-2011-03-02/search_box.pl::- pce_begin_class(brick_search_button, figure).
./explore-2011-03-02/brick_tool.pl::- pce_begin_class(brick_tool, frame).
./explore-2011-03-02/brick_tool.pl::- pce_begin_class(brick_window, ic_canvas).
./explore-2011-03-02/brick_tool.pl::- pce_begin_class(brick_menu_bar, dialog).
./explore-2011-03-02/brick_tool.pl::- pce_begin_class(brick_file_menu, popup).
./explore-2011-03-02/brick_tool.pl::- pce_begin_class(brick_edit_menu, popup).
./explore-2011-03-02/brick_tool.pl::- pce_begin_class(brick_view_menu, popup).
./explore-2011-03-02/brick_tool.pl::- pce_begin_class(brick_data_menu, popup).
./explore-2011-03-02/brick_tool.pl::- pce_begin_class(brick_dialog, dialog).
./explore-2011-03-02/brick_tool.pl::- pce_begin_class(brick_conditions_menu, menu).
./explore-2011-03-02/brick_tool.pl::- pce_begin_class(brick_metric_menu, menu).
./explore-2011-03-02/groenlo.pl::- pce_begin_class(groenlo_token2, brick_token2).
./explore-2011-03-02/wall.pl::- pce_begin_class(wall_token2_sequences, figure).
./explore-2011-03-02/explore_result.pl::- pce_begin_class(seq_explore_result, figure).
./explore-2011-03-02/mod_decorator.pl::- pce_begin_class(mod_decorator, figure).
./explore-2011-03-26/uu/mod_decorator_index.pl::- pce_begin_class(mod_decorator_index, device).
./explore-2011-03-26/uu/mod_brick_sequence.pl::- pce_begin_class(mod_brick_sequence, figure).
./explore-2011-03-26/uu/explore_result.pl::- pce_begin_class(seq_explore_result, figure).
./explore-2011-03-26/uu/mod_decorator.pl::- pce_begin_class(mod_decorator, figure).
./explore-2011-03-26/keep/code.pl::- pce_begin_class(seq_explore_window, mod_canvas).
./explore-2011-03-26/keep/code.pl::- pce_begin_class(seq_explore_result, figure).
./explore-2011-03-26/keep/code.pl::- pce_begin_class(mod_brick_sequence, figure).
./explore-2011-03-26/keep/code.pl::- pce_begin_class(mod_decorator, figure).
./explore-2011-03-26/keep/code.pl::- pce_begin_class(mod_brick_pattern, device).
./explore-2011-03-26/keep/code.pl::- pce_begin_class(mod_brick_any_sequence, mod_brick_pattern).
./explore-2011-03-26/keep/code.pl::- pce_begin_class(mod_brick_user_defined, mod_brick_pattern).
./explore-2011-03-26/keep/code.pl::- pce_begin_class(mod_pattern_define, figure).
./explore-2011-03-26/keep/code.pl::- pce_begin_class(seq_explore_pattern, device).
./explore-2011-03-26/keep/code.pl::- pce_begin_class(seq_explore_index, device).
./explore-2011-03-26/keep/code.pl::- pce_begin_class(mod_decorator_index, device).
./explore-2011-03-26/keep/explore_window.pl::- pce_begin_class(seq_explore_window, seq_canvas).
./explore-2011-03-26/keep/explore_window.pl::- pce_begin_class(seq_explore_result, figure).
./explore-2011-03-26/keep/explore_window.pl::- pce_begin_class(seq_episode_brick, device).
./explore-2011-03-26/keep/explore_window.pl::- pce_begin_class(seq_explore_pattern, device).
./explore-2011-03-26/keep/explore_window.pl::- pce_begin_class(seq_explore_index, device).
./explore-2011-03-26/keep/mod_brick_pattern.pl::- pce_begin_class(mod_brick_pattern, device).
./explore-2011-03-26/keep/mod_brick_pattern.pl::- pce_begin_class(mod_brick_any_sequence, mod_brick_pattern).
./explore-2011-03-26/keep/mod_brick_pattern.pl::- pce_begin_class(mod_brick_user_defined, mod_brick_pattern).
./explore-2011-03-26/brick.pl::- pce_begin_class(brick_base, figure).
./explore-2011-03-26/brick.pl::- pce_begin_class(brick_token2, brick_base).
./explore-2011-03-26/brick.pl::- pce_begin_class(brick_wildcard, brick_token2).
./explore-2011-03-26/brick.pl::- pce_begin_class(brick_meta, brick_base).
./explore-2011-03-26/brick.pl::- pce_begin_class(brick_meta_or, brick_meta).
./explore-2011-03-26/brick.pl::- pce_begin_class(brick_meta_star, brick_meta).
./explore-2011-03-26/brick.pl::- pce_begin_class(brick_meta_optional, brick_meta).
./explore-2011-03-26/brick.pl::- pce_begin_class(brick_meta_exclude, brick_meta).
./explore-2011-03-26/brick.pl::- pce_begin_class(brick_meta_one_or_more, brick_meta).
./explore-2011-03-26/brick.pl::- pce_begin_class(brick_meta_open_bracket, brick_meta).
./explore-2011-03-26/brick.pl::- pce_begin_class(brick_meta_close_bracket, brick_meta).
./explore-2011-03-26/brick.pl::- pce_begin_class(brick_terminator, brick_token2).
./explore-2011-03-26/brick.pl::- pce_begin_class(brick_start, brick_terminator).
./explore-2011-03-26/brick.pl::- pce_begin_class(brick_end, brick_terminator).
./explore-2011-03-26/brick.pl::- pce_begin_class(brick_kleene_star, brick_token2).
./explore-2011-03-26/brick.pl::- pce_begin_class(brick_user_defined, brick_token).
./explore-2011-03-26/brick.pl::- pce_begin_class(brick_pattern_define, figure).
./explore-2011-03-26/brick.pl::- pce_begin_class(brick_index, figure).
./explore-2011-03-26/brick.pl::- pce_begin_class(brick_token2_sequence, figure).
./explore-2011-03-26/brick.pl::- pce_begin_class(brick_pattern_sequence, figure).
./explore-2011-03-26/brick.pl::- pce_begin_class(brick_token2_sequence_base, figure).
./explore-2011-03-26/brick.pl::- pce_begin_class(brick_token2_sequences, brick_token2_sequence_base).
./explore-2011-03-26/brick.pl::- pce_begin_class(brick_sequences_systematic, brick_token2_sequence_base).
./explore-2011-03-26/brick.pl::- pce_begin_class(brick_mine_patterns, brick_token2_sequence_base).
./explore-2011-03-26/brick.pl::- pce_begin_class(brick_token2_sequences_by_condition, brick_token2_sequence_base).
./explore-2011-03-26/search_box.pl::- pce_begin_class(brick_search_box, figure).
./explore-2011-03-26/search_box.pl::- pce_begin_class(brick_search_buttons, figure).
./explore-2011-03-26/search_box.pl::- pce_begin_class(brick_search_button, figure).
./explore-2011-03-26/brick_tool.pl::- pce_begin_class(brick_tool, frame).
./explore-2011-03-26/brick_tool.pl::- pce_begin_class(brick_window, ic_canvas).
./explore-2011-03-26/brick_tool.pl::- pce_begin_class(brick_menu_bar, dialog).
./explore-2011-03-26/brick_tool.pl::- pce_begin_class(brick_file_menu, popup).
./explore-2011-03-26/brick_tool.pl::- pce_begin_class(brick_edit_menu, popup).
./explore-2011-03-26/brick_tool.pl::- pce_begin_class(brick_view_menu, popup).
./explore-2011-03-26/brick_tool.pl::- pce_begin_class(brick_data_menu, popup).
./explore-2011-03-26/brick_tool.pl::- pce_begin_class(brick_dialog, dialog).
./explore-2011-03-26/brick_tool.pl::- pce_begin_class(brick_tseq_menu, menu).
./explore-2011-03-26/brick_tool.pl::- pce_begin_class(brick_conditions_menu, menu).
./explore-2011-03-26/brick_tool.pl::- pce_begin_class(brick_metric_menu, menu).
./explore-2011-03-26/groenlo.pl::- pce_begin_class(groenlo_token2, brick_token2).
./explore-2011-03-26/wall.pl::- pce_begin_class(wall_token2_sequences, figure).
./explore-2011-04-01/uu/mod_brick_sequence.pl::- pce_begin_class(mod_brick_sequence, figure).
./explore-2011-04-01/uu/explore_result.pl::- pce_begin_class(seq_explore_result, figure).
./explore-2011-04-01/keep/code.pl::- pce_begin_class(seq_explore_window, mod_canvas).
./explore-2011-04-01/keep/code.pl::- pce_begin_class(seq_explore_result, figure).
./explore-2011-04-01/keep/code.pl::- pce_begin_class(mod_brick_sequence, figure).
./explore-2011-04-01/keep/code.pl::- pce_begin_class(mod_decorator, figure).
./explore-2011-04-01/keep/code.pl::- pce_begin_class(mod_brick_pattern, device).
./explore-2011-04-01/keep/code.pl::- pce_begin_class(mod_brick_any_sequence, mod_brick_pattern).
./explore-2011-04-01/keep/code.pl::- pce_begin_class(mod_brick_user_defined, mod_brick_pattern).
./explore-2011-04-01/keep/code.pl::- pce_begin_class(mod_pattern_define, figure).
./explore-2011-04-01/keep/code.pl::- pce_begin_class(seq_explore_pattern, device).
./explore-2011-04-01/keep/code.pl::- pce_begin_class(seq_explore_index, device).
./explore-2011-04-01/keep/code.pl::- pce_begin_class(mod_decorator_index, device).
./explore-2011-04-01/keep/explore_window.pl::- pce_begin_class(seq_explore_window, seq_canvas).
./explore-2011-04-01/keep/explore_window.pl::- pce_begin_class(seq_explore_result, figure).
./explore-2011-04-01/keep/explore_window.pl::- pce_begin_class(seq_episode_brick, device).
./explore-2011-04-01/keep/explore_window.pl::- pce_begin_class(seq_explore_pattern, device).
./explore-2011-04-01/keep/explore_window.pl::- pce_begin_class(seq_explore_index, device).
./explore-2011-04-01/keep/mod_brick_pattern.pl::- pce_begin_class(mod_brick_pattern, device).
./explore-2011-04-01/keep/mod_brick_pattern.pl::- pce_begin_class(mod_brick_any_sequence, mod_brick_pattern).
./explore-2011-04-01/keep/mod_brick_pattern.pl::- pce_begin_class(mod_brick_user_defined, mod_brick_pattern).
./explore-2011-04-01/decorator.pl::- pce_begin_class(brick_decorator_index, device).
./explore-2011-04-01/decorator.pl::- pce_begin_class(brick_decorator, figure).
./explore-2011-04-01/brick.pl::- pce_begin_class(brick_base, figure).
./explore-2011-04-01/brick.pl::- pce_begin_class(brick_token2, brick_base).
./explore-2011-04-01/brick.pl::- pce_begin_class(brick_wildcard, brick_token2).
./explore-2011-04-01/brick.pl::- pce_begin_class(brick_meta, brick_base).
./explore-2011-04-01/brick.pl::- pce_begin_class(brick_meta_or, brick_meta).
./explore-2011-04-01/brick.pl::- pce_begin_class(brick_meta_star, brick_meta).
./explore-2011-04-01/brick.pl::- pce_begin_class(brick_meta_optional, brick_meta).
./explore-2011-04-01/brick.pl::- pce_begin_class(brick_meta_negate, brick_meta).
./explore-2011-04-01/brick.pl::- pce_begin_class(brick_meta_one_or_more, brick_meta).
./explore-2011-04-01/brick.pl::- pce_begin_class(brick_meta_two_or_more, brick_meta).
./explore-2011-04-01/brick.pl::- pce_begin_class(brick_meta_open_bracket, brick_meta).
./explore-2011-04-01/brick.pl::- pce_begin_class(brick_meta_close_bracket, brick_meta).
./explore-2011-04-01/brick.pl::- pce_begin_class(brick_terminator, brick_token2).
./explore-2011-04-01/brick.pl::- pce_begin_class(brick_start, brick_terminator).
./explore-2011-04-01/brick.pl::- pce_begin_class(brick_end, brick_terminator).
./explore-2011-04-01/brick.pl::- pce_begin_class(brick_kleene_star, brick_token2).
./explore-2011-04-01/brick.pl::- pce_begin_class(brick_index, figure).
./explore-2011-04-01/brick.pl::- pce_begin_class(brick_token2_sequence, figure).
./explore-2011-04-01/brick.pl::- pce_begin_class(brick_pattern_sequence, figure).
./explore-2011-04-01/brick.pl::- pce_begin_class(brick_token2_sequence_base, figure).
./explore-2011-04-01/brick.pl::- pce_begin_class(brick_token2_sequences, brick_token2_sequence_base).
./explore-2011-04-01/brick.pl::- pce_begin_class(brick_sequences_systematic, brick_token2_sequence_base).
./explore-2011-04-01/brick.pl::- pce_begin_class(brick_mine_patterns, brick_token2_sequence_base).
./explore-2011-04-01/brick.pl::- pce_begin_class(brick_token2_sequences_by_condition, brick_token2_sequence_base).
./explore-2011-04-01/search_box.pl::- pce_begin_class(brick_search_box, figure).
./explore-2011-04-01/search_box.pl::- pce_begin_class(brick_search_buttons, figure).
./explore-2011-04-01/search_box.pl::- pce_begin_class(brick_search_button, figure).
./explore-2011-04-01/search_box.pl::- pce_begin_class(brick_search_meta_index, figure).
./explore-2011-04-01/brick_tool.pl::- pce_begin_class(brick_tool, frame).
./explore-2011-04-01/brick_tool.pl::- pce_begin_class(brick_window, ic_canvas).
./explore-2011-04-01/brick_tool.pl::- pce_begin_class(brick_menu_bar, dialog).
./explore-2011-04-01/brick_tool.pl::- pce_begin_class(brick_file_menu, popup).
./explore-2011-04-01/brick_tool.pl::- pce_begin_class(brick_edit_menu, popup).
./explore-2011-04-01/brick_tool.pl::- pce_begin_class(brick_view_menu, popup).
./explore-2011-04-01/brick_tool.pl::- pce_begin_class(brick_data_menu, popup).
./explore-2011-04-01/brick_tool.pl::- pce_begin_class(brick_dialog, dialog).
./explore-2011-04-01/brick_tool.pl::- pce_begin_class(brick_tseq_menu, menu).
./explore-2011-04-01/brick_tool.pl::- pce_begin_class(brick_conditions_menu, menu).
./explore-2011-04-01/brick_tool.pl::- pce_begin_class(brick_metric_menu, menu).
./explore-2011-04-01/win_preferences.pl::- pce_begin_class(brick_preferences_tool, frame).
./explore-2011-04-01/win_preferences.pl::- pce_begin_class(brick_preferences_dialog, dialog).
./explore-2011-04-01/groenlo.pl::- pce_begin_class(groenlo_token2, brick_token2).
./explore-2011-04-01/wall.pl::- pce_begin_class(wall_token2_sequences, figure).
./methods/pce_native_matrix_table.pl::- pce_begin_class(native_matrix_table, tabular).
./coding/seq_coding_window.pl::- pce_begin_class(seq_coding_window, seq_canvas).
./coding/coded_chat.pl::- pce_begin_class(coding, object).
./coding/coded_chat.pl::- pce_begin_class(coded_chat, figure).
./coding/coded_chat.pl::- pce_begin_class(coded_chat_list, figure).
./format/gls/pce_centrality.pl::- pce_begin_class(gls_centrality, figure).
./format/gls/tool_gls.pl::- pce_begin_class(gls_tool, ic_tool_class).
./format/gls/tool_gls.pl::- pce_begin_class(gls_menu_bar, dialog).
./format/gls/tool_gls.pl::- pce_begin_class(gls_file_menu, popup).
./format/gls/tool_gls.pl::- pce_begin_class(gls_view_menu, popup).
./format/gls/tool_gls.pl::- pce_begin_class(gls_specifications_menu, popup).
./format/gls/tool_gls.pl::- pce_begin_class(mod_edit_menu, popup).
./format/gls/tool_gls.pl::- pce_begin_class(mod_view_menu, popup).
./format/gls/tool_gls.pl::- pce_begin_class(mod_canvas, picture).
./format/gls/tool_gls.pl::- pce_begin_class(model_elements, mod_canvas).
./format/sdm/pce_sdm_model.pl::- pce_begin_class(sdm_window, picture).
./format/sdm/pce_sdm_model.pl::- pce_begin_class(sequence_controller, object).
./format/sdm/pce_sdm_model.pl::- pce_begin_class(sdm_sequence, figure).
./format/sdm/pce_sdm_model.pl::- pce_begin_class(sdm_inquiry_sequence, sdm_sequence).
./format/sdm/pce_sdm_model.pl::- pce_begin_class(sdm_figure, figure).
./format/sdm/pce_sdm_model.pl::- pce_begin_class(sdm_base, figure).
./format/sdm/pce_sdm_model.pl::- pce_begin_class(sdm_relation, sdm_base).
./format/sdm/pce_sdm_model.pl::- pce_begin_class(sdm_stock, sdm_base).
./format/sdm/pce_sdm_model.pl::- pce_begin_class(sdm_dataset, sdm_base).
./format/sdm/pce_sdm_model.pl::- pce_begin_class(sdm_auxiliary, sdm_base).
./format/sdm/pce_sdm_model.pl::- pce_begin_class(sdm_constant, sdm_base).
./format/sdm/pce_sdm_model.pl::- pce_begin_class(sdm_flow, sdm_base).
./format/sdm/pce_sdm_model.pl::- pce_begin_class(flow_diabolo, diabolo).
./format/scy/house.pl::- pce_begin_class(house, figure).
./format/scy/house.pl::- pce_begin_class(house_part, figure).
./format/scy/house.pl::- pce_begin_class(house_roof, house_part).
./format/scy/house.pl::- pce_begin_class(house_door, house_part).
./format/scy/house.pl::- pce_begin_class(house_wall, house_part).
./format/scy/house.pl::- pce_begin_class(house_floor, house_part).
./format/scy/house.pl::- pce_begin_class(house_window, house_part).
./format/zap/samson_2010/gr_progression_plot.pl::- pce_begin_class(q2_progression_plot, frame).
./format/zap/samson_2010/gr_progression_plot.pl::- pce_begin_class(q2_coding_browser, browser).
./format/zap/samson_2010/gr_progression_plot.pl::- pce_begin_class(progression_plot_dialog, dialog).
./format/zap/samson_2010/gr_progression_plot.pl::- pce_begin_class(progression_plot, figure).
./format/cmap/pce_cmap.pl::- pce_begin_class(cmap_figure, figure).
./format/cmap/pce_cmap.pl::- pce_begin_class(cmap_node, figure).
./format/cmap/pce_cmap.pl::- pce_begin_class(cmap_edge, tagged_connection).
./format/simquest/hagemans_2009/cat.pl::- pce_begin_class(cat, figure).
./format/simquest/hagemans_2009/cat.pl::- pce_begin_class(flower, figure).
./format/simquest/hagemans_2009/cat.pl::- pce_begin_class(leaf, arc).
./format/simquest/hagemans_2009/draw_cat.pl::- pce_begin_class(cat, figure).
./format/simquest/hagemans_2009/draw_cat.pl::- pce_begin_class(flower, figure).
./format/simquest/hagemans_2009/draw_cat.pl::- pce_begin_class(leaf, arc).
./format/gaze_tracker/tool_gaze.pl::- pce_begin_class(gaze_tool, ic_tool_class).
./format/gaze_tracker/tool_gaze.pl::- pce_begin_class(gaze_canvas, ic_canvas).
./format/gaze_tracker/tool_gaze.pl::- pce_begin_class(gaze_look_zone, box).
./format/gaze_tracker/tool_gaze.pl::- pce_begin_class(gaze_menu_bar, dialog).
./format/gaze_tracker/tool_gaze.pl::- pce_begin_class(gaze_file_menu, popup).
./format/gaze_tracker/tool_gaze.pl::- pce_begin_class(gaze_export_menu, popup).
./format/gaze_tracker/tool_gaze.pl::- pce_begin_class(gaze_analysis_menu, popup).
./format/gaze_tracker/tool_gaze.pl::- pce_begin_class(gaze_fixation_dialog, dialog).
./format/gaze_tracker/tool_gaze.pl::- pce_begin_class(gaze_source_range, picture).
./format/gaze_tracker/pce_look_zone_path.pl::- pce_begin_class(look_zone_path, figure).
./format/gaze_tracker/pce_look_zone_path.pl::- pce_begin_class(look_zone_path_box, box).
./pce_action_type.pl::- pce_begin_class(action_type_overview, device).
./pce_action_type.pl::- pce_begin_class(action_type_symbol_base, annotation_single).
