
package eu.scy.modules.useradmin.wsclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-02/02/2007 03:56 AM(vivekp)-FCS
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "UserManagement", targetNamespace = "http://impl.webservice.useradmin.modules.scy.eu/", wsdlLocation = "http://localhost:8080/scyadmin/services/UserManagement?wsdl")
public class UserManagement
    extends Service
{

    private final static URL USERMANAGEMENT_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/scyadmin/services/UserManagement?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        USERMANAGEMENT_WSDL_LOCATION = url;
    }

    public UserManagement(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserManagement() {
        super(USERMANAGEMENT_WSDL_LOCATION, new QName("http://impl.webservice.useradmin.modules.scy.eu/", "UserManagement"));
    }

    /**
     * 
     * @return
     *     returns UserManagementService
     */
    @WebEndpoint(name = "UserManagementServiceImplPort")
    public UserManagementService getUserManagementServiceImplPort() {
        return (UserManagementService)super.getPort(new QName("http://impl.webservice.useradmin.modules.scy.eu/", "UserManagementServiceImplPort"), UserManagementService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserManagementService
     */
    @WebEndpoint(name = "UserManagementServiceImplPort")
    public UserManagementService getUserManagementServiceImplPort(WebServiceFeature... features) {
        return (UserManagementService)super.getPort(new QName("http://impl.webservice.useradmin.modules.scy.eu/", "UserManagementServiceImplPort"), UserManagementService.class, features);
    }

}
