/*  $Id$
 *  
 *  File	english.pl
 *  Part of	Amsterdam Intelligent Document Analysis System (AIDAS)
 *  Author	Anjo Anjewierden, anjo@swi.psy.uva.nl
 *  Purpose	English stop words
 *  Works with	SWI-Prolog
 *  
 *  Notice	Copyright (c) 2001, 2004  University of Amsterdam
 *  
 *  History	16/05/01  (Created)
 *  		15/03/04  (Last modified)
 */ 

/*------------------------------------------------------------
 *  Directives
 *------------------------------------------------------------*/

:- module(stoplist_english,
	  []).

/*------------------------------------------------------------
 *  English stop words
 *------------------------------------------------------------*/

stop('a').
stop('about').
stop('above').
stop('across').
stop('after').
stop('afterwards').
stop('again').
stop('against').
stop('all').
stop('almost').
stop('alone').
stop('along').
stop('already').
stop('also').
stop('although').
stop('always').
stop('am').
stop('among').
stop('amongst').
stop('an').
stop('and').
stop('another').
stop('any').
stop('anyhow').
stop('anyone').
stop('anything').
stop('anyway').
stop('anywhere').
stop('are').
stop('aren''t').
stop('around').
stop('as').
stop('at').
stop('back').
stop('be').
stop('became').
stop('because').
stop('become').
stop('becomes').
stop('becoming').
stop('been').
stop('before').
stop('beforehand').
stop('behind').
stop('being').
stop('below').
stop('beside').
stop('besides').
stop('between').
stop('beyond').
stop('both').
stop('but').
stop('by').
stop('can''t').
stop('can').
stop('cannot').
stop('cant').
stop('co').
stop('con').
stop('could').
stop('couldn''t').
stop('couldnt').
stop('cry').
stop('de').
stop('didn''t').
stop('do').
stop('doesn''t').
stop('don''t').
stop('done').
stop('due').
stop('during').
stop('each').
stop('eg').
stop('either').
stop('else').
stop('elsewhere').
stop('enough').
stop('etc').
stop('even').
stop('ever').
stop('every').
stop('everyone').
stop('everything').
stop('everywhere').
stop('except').
stop('few').
stop('fill').
stop('find').
stop('fire').
stop('for').
stop('former').
stop('formerly').
stop('found').
stop('from').
stop('further').
stop('get').
stop('give').
stop('go').
stop('had').
stop('hadn''t').
stop('has').
stop('hasn''t').
stop('hasnt').
stop('have').
stop('haven''t').
stop('he''d').
stop('he''s').
stop('he').
stop('hence').
stop('her').
stop('here''s').
stop('here').
stop('hereafter').
stop('hereby').
stop('herein').
stop('hereupon').
stop('hers').
stop('herself').
stop('him').
stop('himself').
stop('his').
stop('how').
stop('however').
stop('i''d').
stop('i''ll').
stop('i''m').
stop('i''ve').
stop('i').
stop('ie').
stop('if').
stop('in').
stop('indeed').
stop('into').
stop('is').
stop('isn''t').
stop('it''ll').
stop('it''s').
stop('it').
stop('its').
stop('itself').
stop('keep').
stop('last').
stop('latter').
stop('least').
stop('less').
stop('let''s').
stop('made').
stop('many').
stop('may').
stop('me').
stop('meanwhile').
stop('might').
stop('mill').
stop('mine').
stop('more').
stop('moreover').
stop('most').
stop('mostly').
stop('move').
stop('much').
stop('must').
stop('my').
stop('myself').
stop('name').
stop('namely').
stop('neither').
stop('never').
stop('nevertheless').
stop('next').
stop('no').
stop('nobody').
stop('none').
stop('nor').
stop('not').
stop('nothing').
stop('now').
stop('nowhere').
stop('of').
stop('off').
stop('often').
stop('on').
stop('once').
stop('one').
stop('only').
stop('onto').
stop('or').
stop('other').
stop('others').
stop('otherwise').
stop('our').
stop('ours').
stop('ourselves').
stop('out').
stop('over').
stop('own').
stop('part').
stop('per').
stop('perhaps').
stop('please').
stop('put').
stop('rather').
stop('re').
stop('same').
stop('see').
stop('seem').
stop('seemed').
stop('seeming').
stop('seems').
stop('serious').
stop('several').
stop('she').
stop('should').
stop('shouldn''t').
stop('show').
stop('side').
stop('since').
stop('so').
stop('some').
stop('somehow').
stop('someone').
stop('something').
stop('sometime').
stop('sometimes').
stop('somewhere').
stop('still').
stop('such').
stop('take').
stop('than').
stop('that''s').
stop('that').
stop('the').
stop('their').
stop('them').
stop('themselves').
stop('then').
stop('there''s').
stop('there').
stop('thereafter').
stop('thereby').
stop('therefore').
stop('therein').
stop('thereupon').
stop('thereof').
stop('thereon').
stop('these').
stop('they''ll').
stop('they''re').
stop('they''ve').
stop('they').
stop('thin').
stop('this').
stop('those').
stop('though').
stop('through').
stop('throughout').
stop('thru').
stop('thus').
stop('to').
stop('together').
stop('too').
stop('toward').
stop('towards').
stop('under').
stop('until').
stop('up').
stop('upon').
stop('us').
stop('very').
stop('via').
stop('was').
stop('wasn''t').
stop('we''d').
stop('we''ll').
stop('we''re').
stop('we''ve').
stop('we').
stop('well').
stop('were').
stop('what''s').
stop('what').
stop('whatever').
stop('when').
stop('whence').
stop('whenever').
stop('where').
stop('whereafter').
stop('whereas').
stop('whereby').
stop('wherein').
stop('whereupon').
stop('wherever').
stop('whether').
stop('which').
stop('while').
stop('whither').
stop('who''ll').
stop('who''ve').
stop('who').
stop('whoever').
stop('whole').
stop('whom').
stop('whose').
stop('why').
stop('will').
stop('with').
stop('within').
stop('without').
stop('won''t').
stop('would').
stop('wouldn''t').
stop('yet').
stop('you''d').
stop('you''ll').
stop('you''re').
stop('you''ve').
stop('you').
stop('your').
stop('yours').
stop('yourself').
stop('yourselves').
stop('thy').
stop('unto').
stop('yea').
stop('thou').
stop('thee').
stop('ye').
stop('hmm').
stop('hmmm').
stop('hmmmm').
