/*  $Id$
 *  
 *  File	french.pl
 *  Part of	Amsterdam Intelligent Document Analysis System (AIDAS)
 *  Author	Anjo Anjewierden, anjo@swi.psy.uva.nl
 *  Purpose	French stop words
 *  Works with	SWI-Prolog / XPCE
 *  
 *  Notice	Copyright (c) 2001  University of Amsterdam
 *  
 *  History	17/04/01  (Created)
 *  		17/04/01  (Last modified)
 */ 

/*------------------------------------------------------------
 *  French stop words
 *------------------------------------------------------------*/

:- module(stoplist_french,
	  []).

stop('a').
stop('absolument').
stop('adieu').
stop('afin').
stop('ah').
stop('ailleurs').
stop('ainsi').
stop('alentour').
stop('alentours').
stop('all�luia').
stop('all�').
stop('alors').
stop('amen').
stop('apr�s').
stop('assez').
stop('au').
stop('aucun').
stop('aucune').
stop('aujourd').
stop('auparavant').
stop('auquel').
stop('aussi').
stop('aussit�t').
stop('autant').
stop('autour').
stop('autre').
stop('autrefois').
stop('autres').
stop('autrui').
stop('aux').
stop('auxquelles').
stop('auxquels').
stop('avant').
stop('a�e').
stop('bah').
stop('bien').
stop('bient�t').
stop('bis').
stop('bof').
stop('bonjour').
stop('bonsoir').
stop('bravo').
stop('brrr').
stop('c').
stop('car').
stop('car or').
stop('ce').
stop('cela').
stop('celle').
stop('celles').
stop('celui').
stop('certain').
stop('certaine').
stop('ces').
stop('cette').
stop('ceux').
stop('chaque').
stop('chez').
stop('chic').
stop('chiche').
stop('chose').
stop('choses').
stop('chut').
stop('ci').
stop('combien').
stop('comme').
stop('comment').
stop('compl�tement').
stop('concernant').
stop('contre').
stop('d').
stop('dans').
stop('davantage').
stop('de').
stop('debout').
stop('dedans').
stop('dehors').
stop('demain').
stop('depuis').
stop('derechef').
stop('des').
stop('desquelles').
stop('desquels').
stop('dessous').
stop('dessus').
stop('devant').
stop('diff�rent').
stop('diff�rente').
stop('diff�rentes').
stop('diff�rents').
stop('dire').
stop('divers').
stop('diverse').
stop('diverses').
stop('dont').
stop('dor�navant').
stop('du').
stop('duquel').
stop('d�s').
stop('d�j�').
stop('d�sormais').
stop('elle').
stop('elles').
stop('en').
stop('encontre').
stop('encore').
stop('enfin').
stop('ensemble').
stop('ensuite').
stop('enti�rement').
stop('entre').
stop('envers').
stop('es').
stop('est').
stop('et').
stop('eux').
stop('expr�s').
stop('faire').
stop('fais').
stop('faisons').
stop('fait').
stop('faites').
stop('fi').
stop('fl�te').
stop('font').
stop('foutre').
stop('franco').
stop('gratis').
stop('halte').
stop('hein').
stop('hello').
stop('hep').
stop('hier').
stop('hormis').
stop('hors').
stop('hosanna').
stop('hourra').
stop('hui').
stop('h�').
stop('h�las').
stop('ici').
stop('il').
stop('ils').
stop('impromptu').
stop('incognito').
stop('incontinent').
stop('jadis').
stop('jamais').
stop('je').
stop('jusqu').
stop('jusque').
stop('l').
stop('la').
stop('ladite').
stop('laquelle').
stop('le').
stop('ledit').
stop('lequel').
stop('les').
stop('lesdites').
stop('lesdits').
stop('lesquelles').
stop('lesquels').
stop('leur').
stop('leurs').
stop('loin').
stop('longtemps').
stop('lors').
stop('lorsqu').
stop('lorsque').
stop('lui').
stop('l�').
stop('ma').
stop('maint').
stop('mainte').
stop('maintenant').
stop('maintes').
stop('maints').
stop('mais').
stop('mal').
stop('malgr�').
stop('me').
stop('merci').
stop('merde').
stop('mes').
stop('miam').
stop('mien').
stop('mienne').
stop('mieux').
stop('mince').
stop('moi').
stop('moins').
stop('mon').
stop('motus').
stop('moyennant').
stop('m�me').
stop('m�mes').
stop('na').
stop('nagu�re').
stop('ne').
stop('nenni').
stop('ni').
stop('non').
stop('nonobstant').
stop('nos').
stop('notre').
stop('nous').
stop('nul').
stop('nulle').
stop('n�ant').
stop('n�ants').
stop('n�tre').
stop('n�tres').
stop('oh').
stop('ok').
stop('on').
stop('ou').
stop('ouest').
stop('ouf').
stop('oui').
stop('ouille').
stop('outre').
stop('o�').
stop('par').
stop('parce').
stop('parfois').
stop('parmi').
stop('partir').
stop('partout').
stop('pas').
stop('passablement').
stop('pendant').
stop('personne').
stop('peu').
stop('peuh').
stop('pis').
stop('plus').
stop('plusieurs').
stop('plut�t').
stop('pouah').
stop('pouce').
stop('pour').
stop('proche').
stop('pr�s').
stop('psstt').
stop('puis').
stop('puisqu').
stop('puisque').
stop('qu').
stop('quand').
stop('quasiment').
stop('que').
stop('quel').
stop('quelconque').
stop('quelconques').
stop('quelle').
stop('quelles').
stop('quelque').
stop('quelquefois').
stop('quelques').
stop('quels').
stop('qui').
stop('quiconque').
stop('quoi').
stop('quoiqu').
stop('quoique').
stop('recta').
stop('rien').
stop('s').
stop('sa').
stop('sans').
stop('sauf').
stop('se').
stop('selon').
stop('ses').
stop('si').
stop('sien').
stop('sienne').
stop('sit�t').
stop('soi').
stop('soient').
stop('soit').
stop('sommes').
stop('son').
stop('sont').
stop('sos').
stop('soudain').
stop('sous').
stop('souvent').
stop('stop').
stop('subito').
stop('suffisamment').
stop('suis').
stop('suivant').
stop('sur').
stop('sus').
stop('ta').
stop('tant').
stop('tant�t').
stop('tard').
stop('te').
stop('tel').
stop('telle').
stop('tellement').
stop('telles').
stop('tels').
stop('tes').
stop('tien').
stop('tienne').
stop('toi').
stop('ton').
stop('totalement').
stop('touchant').
stop('toujours').
stop('tous').
stop('tout').
stop('toute').
stop('toutes').
stop('tu').
stop('t�t').
stop('un').
stop('une').
stop('vers').
stop('via').
stop('vite').
stop('vivat').
stop('voici').
stop('voil�').
stop('voire').
stop('volontiers').
stop('vos').
stop('votre').
stop('vous').
stop('v�tre').
stop('v�tres').
stop('y').
stop('zut').
stop('�').
stop('�a').
stop('��').
stop('�gard').
stop('�tes').
stop('�tre').
