/*  $Id$
 *  
 *  File	spanish.pl
 *  Part of	Amsterdam Intelligent Document Analysis System (AIDAS)
 *  Author	Anjo Anjewierden, anjo@swi.psy.uva.nl
 *  Purpose	Spanish stop words
 *  Works with	SWI-Prolog / XPCE
 *  
 *  Notice	Copyright (c) 2001  University of Amsterdam
 *  
 *  History	17/05/01  (Created)
 *  		17/05/01  (Last modified)
 */ 

/*------------------------------------------------------------
 *  Directives
 *------------------------------------------------------------*/

:- module(stoplist_spanish,
	  []).


/*------------------------------------------------------------
 *  Spanish stop words
 *------------------------------------------------------------*/

stop('�l').
stop('Sr').
stop('Sra').
stop('Sres').
stop('Sta').
stop('a').
stop('aca�').
stop('ah�').
stop('ajena').
stop('ajenas').
stop('ajeno').
stop('ajenos').
stop('al').
stop('alg�n').
stop('algo').
stop('alguna').
stop('algunas').
stop('alguno').
stop('algunos').
stop('all�').
stop('all�').
stop('aqu�').
stop('aquel').
stop('aquella').
stop('aquellas').
stop('aquello').
stop('aquellos').
stop('c�mo').
stop('cada').
stop('cierta').
stop('ciertas').
stop('cierto').
stop('ciertos').
stop('como').
stop('con').
stop('conmigo').
stop('consigo').
stop('contigo').
stop('cu�n').
stop('cu�nta').
stop('cu�ntas').
stop('cu�nto').
stop('cu�ntos').
stop('cualquier').
stop('cualquiera').
stop('cualquieras').
stop('cuan').
stop('cuanta').
stop('cuantas').
stop('cuanto').
stop('cuantos').
stop('de').
stop('dejar').
stop('del').
stop('dem�s').
stop('demasiada').
stop('demasiadas').
stop('demasiado').
stop('demasiados').
stop('el').
stop('ella').
stop('ellas').
stop('ellos').
stop('esa').
stop('esas').
stop('ese').
stop('esos').
stop('esta').
stop('estar').
stop('estas').
stop('este').
stop('estos').
stop('hacer').
stop('hasta').
stop('jam�s').
stop('junto').
stop('juntos').
stop('la').
stop('las').
stop('lo').
stop('los').
stop('m�s').
stop('m�a').
stop('m�o').
stop('mas').
stop('me').
stop('menos').
stop('mientras').
stop('misma').
stop('mismas').
stop('mismo').
stop('mismos').
stop('much�sima').
stop('much�simas').
stop('much�simo').
stop('much�simos').
stop('mucha').
stop('muchas').
stop('mucho').
stop('muchos').
stop('muy').
stop('nada').
stop('ni').
stop('ninguna').
stop('ningunas').
stop('ninguno').
stop('ningunos').
stop('no').
stop('nos').
stop('nosotras').
stop('nosotros').
stop('nuestra').
stop('nuestras').
stop('nuestro').
stop('nuestros').
stop('nunca').
stop('os').
stop('otra').
stop('otras').
stop('otro').
stop('otros').
stop('para').
stop('parecer').
stop('poca').
stop('pocas').
stop('poco').
stop('pocos').
stop('por').
stop('porque').
stop('qu�').
stop('que').
stop('querer').
stop('qui�n').
stop('quien').
stop('quienes').
stop('quienesquiera').
stop('quienquiera').
stop('s�').
stop('s�n').
stop('ser').
stop('si').
stop('siempre').
stop('suya').
stop('suyas').
stop('suyo').
stop('suyos').
stop('t�').
stop('tal').
stop('tales').
stop('tan').
stop('tanta').
stop('tantas').
stop('tanto').
stop('tantos').
stop('te').
stop('tener').
stop('ti').
stop('toda').
stop('todas').
stop('todo').
stop('todos').
stop('tomar').
stop('tuya').
stop('tuyo').
stop('un').
stop('una').
stop('unas').
stop('unos').
stop('usted').
stop('ustedes').
stop('varias').
stop('varios').
stop('vosotras').
stop('vosotros').
stop('vuestra').
stop('vuestras').
stop('vuestro').
stop('vuestros').
stop('y').
stop('yo').

