package eu.scy.common.mission;

public enum LasType
{
   ORIENTATION, MANAGEMENT, INFORMATION, CONCEPTUALISATION, DEBATE, REFLECTION, ANALYSIS, DESIGN, 
   CONSTRUCTION, EXPERIMENT, EVALUATION, REGULATION, REPORTING
}
