/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EdPFrame.java
 *
 * Created on 6 avr. 2009, 15:52:59
 */

package eu.scy.tools.copex.edp;

import eu.scy.tools.copex.common.LearnerProcedure;
import eu.scy.tools.copex.utilities.ActionCopex;
import java.awt.BorderLayout;
import javax.swing.UIManager;

/**
 * test frame edp
 * @author Marjolaine
 */
public class EdPFrame extends javax.swing.JFrame implements ActionCopex{
    private CopexPanel copex;

    /** Creates new form EdPFrame */
    public EdPFrame() {
        super();
        initComponents();
        initEdP();
    }

    public void load(){
        copex.loadData();
        setSize(695,495);
    }
    private void initEdP(){
        copex = new CopexPanel(false);
        copex.addActionCopex(this);
        add(copex, BorderLayout.CENTER);
        setSize(CopexPanel.PANEL_WIDTH, CopexPanel.PANEL_HEIGHT);
    }

    

   


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("COPEX- Experimental Design Tool");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        // Initialisation du look and feel
        try{
            String myLookAndFeel=UIManager.getSystemLookAndFeelClassName();
            UIManager.setLookAndFeel(myLookAndFeel);
        }catch(Exception e){
            System.out.println("ERREUR dans l'initialisation du lookAndFeel : "+e) ;
            //JOptionPane.showMessageDialog(this , "ERREUR ans l'initialisation du lookAndFeel : "+e, "ERROR",JOptionPane.ERROR_MESSAGE);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EdPFrame edPFrame =new EdPFrame();
                edPFrame.setVisible(true);
                edPFrame.load();
            }
        });
        
    }

    @Override
    public void loadHelpProc(LearnerProcedure helpProc) {
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
