/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CloseDatasetDialog.java
 *
 * Created on 21 sept. 2009, 20:41:59
 */

package eu.scy.client.tools.dataProcessTool.dataTool;

import eu.scy.client.tools.fitex.main.DataProcessToolPanel;
import eu.scy.client.tools.dataProcessTool.common.Dataset;
import eu.scy.client.tools.dataProcessTool.utilities.MyUtilities;

/**
 * close or remove the dataset(in labbook)
 * @author Marjolaine
 */
public class CloseDatasetDialog extends javax.swing.JDialog {
    private DataProcessToolPanel owner;
    private Dataset dataset;

    public CloseDatasetDialog(DataProcessToolPanel owner, Dataset dataset) {
        super();
        this.owner = owner;
        this.dataset = dataset;
        initComponents();
        initGUI();
        setResizable(false);
        setModal(true);
        setLocationRelativeTo(owner);
    }


    /** Creates new form CloseDatasetDialog */
    public CloseDatasetDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }


    private void initGUI(){
        // parameters in the radiobutton
        String s = owner.getBundleString("LABEL_CLOSE_DATASET");
        s = MyUtilities.replace(s,0, dataset.getName());
        rbClose.setText(s);
        s = owner.getBundleString("LABEL_DELETE_DATASET");
        s = MyUtilities.replace(s,0, dataset.getName());
        rbDelete.setText(s);
        this.rbClose.setSize(60+MyUtilities.lenghtOfString(this.rbClose.getText(), getFontMetrics(this.rbClose.getFont())), this.rbClose.getHeight());
        // rb delete
        this.rbDelete.setSize(60+MyUtilities.lenghtOfString(this.rbDelete.getText(), getFontMetrics(this.rbDelete.getFont())), this.rbDelete.getHeight());
        // ok button
        this.buttonOk.setSize(MyUtilities.lenghtOfString(this.buttonOk.getText(), getFontMetrics(this.buttonOk.getFont())), this.buttonOk.getHeight());
        // cancel button
        this.buttonCancel.setSize(MyUtilities.lenghtOfString(this.buttonCancel.getText(), getFontMetrics(this.buttonCancel.getFont())), this.buttonCancel.getHeight());
    }


    private void validDialog(){
        boolean close = rbClose.isSelected();
        boolean isOk = true;
        if(close)
            isOk = owner.closeDataset(dataset);
        else
            isOk =owner.removeDataset(dataset);
        if(isOk)
            this.dispose();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbClose = new javax.swing.JRadioButton();
        rbDelete = new javax.swing.JRadioButton();
        buttonOk = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        rbClose.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbClose.setSelected(true);
        rbClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCloseActionPerformed(evt);
            }
        });

        rbDelete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDeleteActionPerformed(evt);
            }
        });

        buttonOk.setText(owner.getBundleString("BUTTON_OK"));
        buttonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOkActionPerformed(evt);
            }
        });

        buttonCancel.setText(owner.getBundleString("BUTTON_CANCEL"));
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(buttonOk)
                        .addGap(93, 93, 93)
                        .addComponent(buttonCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbClose, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbClose)
                .addGap(18, 18, 18)
                .addComponent(rbDelete)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonOk)
                    .addComponent(buttonCancel))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCloseActionPerformed
        rbClose.setSelected(true);
        rbDelete.setSelected(false);
    }//GEN-LAST:event_rbCloseActionPerformed

    private void rbDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDeleteActionPerformed
        rbClose.setSelected(false);
        rbDelete.setSelected(true);
    }//GEN-LAST:event_rbDeleteActionPerformed

    private void buttonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOkActionPerformed
        validDialog();
    }//GEN-LAST:event_buttonOkActionPerformed

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonCancelActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CloseDatasetDialog dialog = new CloseDatasetDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonOk;
    private javax.swing.JRadioButton rbClose;
    private javax.swing.JRadioButton rbDelete;
    // End of variables declaration//GEN-END:variables


}
