/*  $Id$
 *  
 *  File	dutch.pl
 *  Part of	Amsterdam Intelligent Document Analysis System (AIDAS)
 *  Author	Anjo Anjewierden, anjo@science.uva.nl
 *  Purpose	Dutch stop words
 *  Works with	SWI-Prolog (www.swi-prolog.org)
 *  
 *  Notice	Copyright (c) 2001, 2004  University of Amsterdam
 *  
 *  History	17/05/01  (Created)
 *  		14/05/07  (Last modified)
 */ 

/*------------------------------------------------------------
 *  Directives
 *------------------------------------------------------------*/

:- module(stoplist_dutch,
	  []).


/*------------------------------------------------------------
 *  Dutch stop words
 *------------------------------------------------------------*/

stop(aan).
stop(aangezien).
stop(achter).
stop(achterna).
stop(afgelopen).
stop(af).
stop(al).
stop(aldaar).
stop(aldus).
stop(alhoewel).
stop(alle).
stop(allebei).
stop(alleen).
stop(als).
stop(alsnog).
stop(altijd).
stop(altoos).
stop(ander).
stop(andere).
stop(anders).
stop(anderszins).
stop(behalve).
stop(behoudens).
stop(beide).
stop(beiden).
stop(ben).
stop(bent).
stop(bepaald).
stop(betreffende).
stop(bij).
stop(binnen).
stop(binnenin).
stop(boven).
stop(bovenal).
stop(bovendien).
stop(bovengenoemd).
stop(bovenstaand).
stop(bovenvermeld).
stop(buiten).
stop(daar).
stop(daardoor).
stop(daarheen).
stop(daarin).
stop(daarna).
stop(daarnet).
stop(daarom).
stop(daarop).
stop(daarvanlangs).
stop(dan).
stop(dat).
stop(de).
stop(deze).
stop(die).
stop(dikwijls).
stop(dit).
stop(door).
stop(doorgaand).
stop(dus).
stop(echter).
stop(eer).
stop(eerdat).
stop(eerder).
stop(eerlang).
stop(eerst).
stop(eh).
stop(ehm).
stop(eigenlijk).
stop(elk).
stop(elke).
stop(en).
stop(een).
stop(enig).
stop(enigszins).
stop(enkel).
stop(er).
stop(erdoor).
stop(even).
stop(eveneens).
stop(evenwel).
stop(gauw).
stop(gedurende).
stop(geen).
stop(gehad).
stop(gekund).
stop(geleden).
stop(gelijk).
stop(gemoeten).
stop(gemogen).
stop(geweest).
stop(gewoon).
stop(gewoonweg).
stop(haar).
stop(had).
stop(hadden).
stop(hare).
stop(heb).
stop(hebben).
stop(hebt).
stop(heel).
stop(helemaal).
stop(hier).
stop(hierbij).
stop(mogelijk).
stop(nodig).
stop(heeft).
stop(hem).
stop(hen).
stop(het).
stop(hierbeneden).
stop(hierboven).
stop(hij).
stop(hoe).
stop(hoewel).
stop(hun).
stop(hunne).
stop(ik).
stop(ikzelf).
stop(in).
stop(inmiddels).
stop(inzake).
stop(is).
stop(ja).
stop(jezelf).
stop(je).
stop(jij).
stop(jijzelf).
stop(jou).
stop(jouw).
stop(jouwe).
stop(juist).
stop(jullie).
stop(kan).
stop(klaar).
stop(kon).
stop(konden).
stop(krachtens).
stop(kunnen).
stop(kunt).
stop(later).
stop(liever).
stop(maar).
stop(mag).
stop(meer).
stop(met).
stop(mezelf).
stop(mij).
stop(mijn).
stop(mijnent).
stop(mijner).
stop(mijzelf).
stop(misschien).
stop(mocht).
stop(mochten).
stop(moest).
stop(moesten).
stop(moet).
stop(moeten).
stop(mogen).
stop(na).
stop(naar).
stop(nadat).
stop(net).
stop(niet).
stop(noch).
stop(nog).
stop(nogal).
stop(nou).
stop(nu).
stop(of).
stop(ofschoon).
stop(om).
stop(omdat).
stop(omhoog).
stop(omlaag).
stop(omstreeks).
stop(omtrent).
stop(omver).
stop(ondertussen).
stop(ongeveer).
stop(ons).
stop(onszelf).
stop(onze).
stop(ook).
stop(op).
stop(opnieuw).
stop(opzij).
stop(over).
stop(overeind).
stop(overigens).
stop(precies).
stop(reeds).
stop(rond).
stop(rondom).
stop(sedert).
stop(sinds).
stop(sindsdien).
stop(slechts).
stop(sommige).
stop(spoedig).
stop(steeds).
stop(tamelijk).
stop(te).
stop(tenzij).
stop(terwijl).
stop(thans).
stop(tijdens).
stop(toch).
stop(toen).
stop(toenmaals).
stop(toenmalig).
stop(tot).
stop(totdat).
stop(tussen).
stop(uhm).
stop(uit).
stop(uw).
stop(vaak).
stop(van).
stop(vandaan).
stop(vanuit).
stop(vanwege).
stop(veel).
stop(veeleer).
stop(verder).
stop(vervolgens).
stop(vol).
stop(volgens).
stop(voor).
stop(vooraf).
stop(vooral).
stop(vooralsnog).
stop(voorbij).
stop(voordat).
stop(voordezen).
stop(voordien).
stop(voorheen).
stop(voorop).
stop(vooruit).
stop(vrij).
stop(vroeg).
stop(waar).
stop(waardoor).
stop(waarom).
stop(waarbij).
stop(wanneer).
stop(want).
stop(waren).
stop(was).
stop(wat).
stop(we).
stop(weer).
stop(wegens).
stop(wel).
stop(weldra).
stop(welk).
stop(welke).
stop(wie).
stop(wiens).
stop(wier).
stop(wij).
stop(wijzelf).
stop(wordt).
stop(word).
stop(werd).
stop(zal).
stop(ze).
stop(zeg).
stop(zelfs).
stop(zichzelf).
stop(zich).
stop(zij).
stop(zijn).
stop(zijne).
stop(zo).
stop(zodra).
stop(zonder).
stop(zou).
stop(zouden).
stop(zowat).
stop(zulke).
stop(zullen).
stop(zult).

