/*  $Id$
 *  
 *  File	german.pl
 *  Part of	Amsterdam Intelligent Document Analysis System (AIDAS)
 *  Author	Anjo Anjewierden, anjo@swi.psy.uva.nl
 *  Purpose	German stop words
 *  Works with	SWI-Prolog / XPCE
 *  
 *  Notice	Copyright (c) 2001  University of Amsterdam
 *  
 *  History	17/05/01  (Created)
 *  		18/05/01  (Last modified)
 */ 

/*------------------------------------------------------------
 *  Directives
 *------------------------------------------------------------*/

:- module(stoplist_german,
	  []).


/*------------------------------------------------------------
 *  German stop words
 *------------------------------------------------------------*/

stop('�ber').
stop('Ihnen').
stop('Ihre').
stop('Ihrem').
stop('Ihren').
stop('Ihrer').
stop('Ihres').
stop('Sie').
stop('ab').
stop('aber').
stop('allein').
stop('als').
stop('also').
stop('am').
stop('an').
stop('au�er').
stop('ausser').
stop('auch').
stop('auf').
stop('aus').
stop('bald').
stop('bei').
stop('beim').
stop('bi�chen').
stop('bisschen').
stop('bin').
stop('bis').
stop('bist').
stop('da').
stop('da�').
stop('dass').
stop('dabei').
stop('dadurch').
stop('daf�r').
stop('dagegen').
stop('dahinter').
stop('damit').
stop('danach').
stop('daneben').
stop('dann').
stop('dar�ber').
stop('daran').
stop('darauf').
stop('daraus').
stop('darin').
stop('darum').
stop('darunter').
stop('das').
stop('dasselbe').
stop('davon').
stop('davor').
stop('dazu').
stop('dazwischen').
stop('dein').
stop('deine').
stop('deinem').
stop('deinen').
stop('deiner').
stop('deines').
stop('dem').
stop('demselben').
stop('den').
stop('denn').
stop('der').
stop('derselben').
stop('des').
stop('desselben').
stop('dessen').
stop('dich').
stop('die').
stop('dies').
stop('diese').
stop('dieselbe').
stop('dieselben').
stop('diesem').
stop('diesen').
stop('dieser').
stop('dieses').
stop('dir').
stop('doch').
stop('dort').
stop('du').
stop('ebenso').
stop('ehe').
stop('ein').
stop('eine').
stop('einem').
stop('einen').
stop('einer').
stop('eines').
stop('entlang').
stop('er').
stop('es').
stop('etwa').
stop('etwas').
stop('euch').
stop('euer').
stop('eure').
stop('eurem').
stop('euren').
stop('eurer').
stop('eures').
stop('f�r').
stop('f�rs').
stop('ganz').
stop('gar').
stop('gegen').
stop('genau').
stop('gewesen').
stop('her').
stop('herein').
stop('herum').
stop('hin').
stop('hinter').
stop('hintern').
stop('ich').
stop('ihm').
stop('ihn').
stop('ihnen').
stop('ihr').
stop('ihre').
stop('ihrem').
stop('ihren').
stop('ihrer').
stop('ihres').
stop('im').
stop('in').
stop('ist').
stop('ja').
stop('je').
stop('jedesmal').
stop('jedoch').
stop('jene').
stop('jenem').
stop('jenen').
stop('jener').
stop('jenes').
stop('kaum').
stop('kein').
stop('keine').
stop('keinem').
stop('keinen').
stop('keiner').
stop('keines').
stop('man').
stop('mehr').
stop('mein').
stop('meine').
stop('meinem').
stop('meinen').
stop('meiner').
stop('meines').
stop('mich').
stop('mir').
stop('mit').
stop('n�mlich').
stop('nach').
stop('nachdem').
stop('neben').
stop('nein').
stop('nicht').
stop('nichts').
stop('noch').
stop('nun').
stop('nur').
stop('ob').
stop('ober').
stop('obgleich').
stop('oder').
stop('ohne').
stop('paar').
stop('sehr').
stop('sei').
stop('sein').
stop('seine').
stop('seinem').
stop('seinen').
stop('seiner').
stop('seines').
stop('seit').
stop('seitdem').
stop('selbst').
stop('sich').
stop('sie').
stop('sind').
stop('so').
stop('sogar').
stop('solch').
stop('solche').
stop('solchem').
stop('solchen').
stop('solcher').
stop('solches').
stop('sondern').
stop('sonst').
stop('soviel').
stop('soweit').
stop('um').
stop('und').
stop('uns').
stop('unser').
stop('unsre').
stop('unsrem').
stop('unsren').
stop('unsrer').
stop('unsres').
stop('vom').
stop('von').
stop('vor').
stop('welche').
stop('w�hrend').
stop('w�re').
stop('w�ren').
stop('war').
stop('warum').
stop('was').
stop('wegen').
stop('weil').
stop('weit').
stop('welchem').
stop('welchen').
stop('welcher').
stop('welches').
stop('wem').
stop('wen').
stop('wenn').
stop('wer').
stop('weshalb').
stop('wessen').
stop('wie').
stop('wir').
stop('wo').
stop('womit').
stop('zu').
stop('zum').
stop('zur').
stop('zwar').
stop('zwischen').
stop('zwischens').

