/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


package eu.scy.tools.dataProcessTool.dataTool;

import eu.scy.tools.dataProcessTool.utilities.DataConstants;
import eu.scy.tools.dataProcessTool.utilities.MyUtilities;
import java.io.File;

/**
 * importCsvDialog to determine the separator field (; or,) and the separator text (nothing or "")
 * @author Marjolaine
 */
public class ImportCsvDialog extends javax.swing.JDialog {
    private FitexToolPanel owner;

    public ImportCsvDialog(FitexToolPanel owner) {
        super();
        this.owner = owner;
        initComponents();
        setLocation(owner.getLocationDialog());
        setModal(true);
        setModalityType(DEFAULT_MODALITY_TYPE);
        setResizable(false);
        initGUI();
    }
    

    /** Creates new form ImportCsvDialog */
    public ImportCsvDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    private void initGUI(){
        labelSepField.setSize(MyUtilities.lenghtOfString(this.labelSepField.getText(), getFontMetrics(this.labelSepField.getFont())), labelSepField.getHeight());
        labelSepText.setSize(MyUtilities.lenghtOfString(this.labelSepText.getText(), getFontMetrics(this.labelSepText.getFont())), labelSepText.getHeight());
        cbSeparatorField.addItem(DataConstants.CSV_SEPARATOR_COMMA);
        cbSeparatorField.addItem(DataConstants.CSV_SEPARATOR_SEMICOLON);
        cbSeparatorText.addItem(DataConstants.CSV_SEPARATOR_TEXT);
        cbSeparatorText.addItem(DataConstants.CSV_SEPARATOR_TEXT_QUOTATION_MARK);
        buttonOk.setSize(60+MyUtilities.lenghtOfString(this.buttonOk.getText(), getFontMetrics(this.buttonOk.getFont())), buttonOk.getHeight());
        buttonCancel.setSize(60+MyUtilities.lenghtOfString(this.buttonCancel.getText(), getFontMetrics(this.buttonCancel.getFont())), buttonCancel.getHeight());
    }

    private void updateSeparatorField(){
        String sepField = (String)cbSeparatorField.getSelectedItem();
        boolean displayText = sepField.equals(DataConstants.CSV_SEPARATOR_COMMA);
        labelSepText.setVisible(displayText);
        cbSeparatorText.setVisible(displayText);
        repaint();
    }

    private void doImport(){
        String sepField = (String)cbSeparatorField.getSelectedItem();
        String sepText = null;
        if(sepField.equals(DataConstants.CSV_SEPARATOR_COMMA)){
            sepText = (String)cbSeparatorText.getSelectedItem();
        }
        owner.importCsvData(sepField, sepText);
        this.dispose();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelSepField = new javax.swing.JLabel();
        cbSeparatorField = new javax.swing.JComboBox();
        labelSepText = new javax.swing.JLabel();
        cbSeparatorText = new javax.swing.JComboBox();
        buttonOk = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(owner.getBundleString("TITLE_DIALOG_IMPORT_CSV"));
        setModal(true);
        setResizable(false);

        labelSepField.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelSepField.setText(owner.getBundleString("LABEL_SEPARATOR_FIELD"));

        cbSeparatorField.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbSeparatorFieldItemStateChanged(evt);
            }
        });

        labelSepText.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelSepText.setText(owner.getBundleString("LABEL_SEPARATOR_TEXT"));

        buttonOk.setText(owner.getBundleString("BUTTON_OK"));
        buttonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOkActionPerformed(evt);
            }
        });

        buttonCancel.setText(owner.getBundleString("BUTTON_CANCEL"));
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelSepField)
                                .addGap(18, 18, 18)
                                .addComponent(cbSeparatorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelSepText)
                                .addGap(18, 18, 18)
                                .addComponent(cbSeparatorText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(buttonOk)
                        .addGap(51, 51, 51)
                        .addComponent(buttonCancel)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSepField)
                    .addComponent(cbSeparatorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSepText)
                    .addComponent(cbSeparatorText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonOk)
                    .addComponent(buttonCancel))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        owner.importCsvData(null, null);
        this.dispose();
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void buttonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOkActionPerformed
        doImport();
    }//GEN-LAST:event_buttonOkActionPerformed

    private void cbSeparatorFieldItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbSeparatorFieldItemStateChanged
        updateSeparatorField();
    }//GEN-LAST:event_cbSeparatorFieldItemStateChanged

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ImportCsvDialog dialog = new ImportCsvDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonOk;
    private javax.swing.JComboBox cbSeparatorField;
    private javax.swing.JComboBox cbSeparatorText;
    private javax.swing.JLabel labelSepField;
    private javax.swing.JLabel labelSepText;
    // End of variables declaration//GEN-END:variables

}
