/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package eu.scy.client.desktop.scydesktop.tooltips;

/**
 *
 * @author SikkenJ
 */
public enum BubbleKey
{

   CLOSED_ELO_BUDDIES,
   OPEN_ELO_BUDDIES,
   DRAWER_CONTROL,
   DRAWER_TAGGING_CONTROL,
   DRAWER_FEEDBACK_CONTROL,
   DRAWER_RESOURCES_CONTROL,
   DRAWER_ASSIGNMENT_CONTROL,
   ARCHIVER_DRAG,
   NEW_ELO_FROM_TEMPLATE,
   SEARCH_CLICK,
   SEARCH_DRAG,
   NEW_BLANK_ELO,
   ELO_ICON_CLOSED,
   ELO_ICON_OPEN,
   ELO_CLOSED,
   ELO_OPEN,
   LAS_CURTAIN_CONTROL,
   MISSION_MAP_CONTROL,
   MISION_MAP_CURTAIN_CONTROL,
   MISSION_MAP_CLOSE,
   MISSION_MAP_ANCHOR_ELO_HOVER,
   MISSION_MAP_ANCHOR_ELO_CLICK,

}
