
package eu.scy.modules.useradmin.wsclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-02/02/2007 03:56 AM(vivekp)-FCS
 * Generated source version: 2.1
 * 
 */
@WebService(name = "UserManagementService", targetNamespace = "http://www.scy-net.eu/schemas")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserManagementService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "loginUser", targetNamespace = "http://www.scy-net.eu/schemas", className = "eu.scy.modules.useradmin.wsclient.LoginUser")
    @ResponseWrapper(localName = "loginUserResponse", targetNamespace = "http://www.scy-net.eu/schemas", className = "eu.scy.modules.useradmin.wsclient.LoginUserResponse")
    public String loginUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
