/*
 * FunctionPlotter.java
 *
 * Created on 11 mai 2007, 16:19
 */ 

package eu.scy.tools.fitex.GUI;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;


/**
 *
 * @author  Cedric
 */
public class MainInterface extends javax.swing.JFrame implements ActionFitex {
   /* version */
    private String version = "3.0";
    /* fitex panel */
    private FitexPanel fitexPanel;
    /* table de données */
    private DataTable dataTable;
    
    /** Creates new form FunctionPlotter */
    public MainInterface() {
        super();
        initComponents();
        setTitle("FITEX "+version);
        getContentPane().add(getFitexPanel(), BorderLayout.CENTER);
        dataTable = new DataTable(fitexPanel);
        setSize(600,450);
    }

    private FitexPanel getFitexPanel(){
        if(fitexPanel == null){
            fitexPanel = new FitexPanel();
            fitexPanel.setName("fitexPanel");
            fitexPanel.addActionFitex(this);
        }
        return fitexPanel;
    }
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    // Set System L&F
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (UnsupportedLookAndFeelException e) {
                    // handle exception
                } catch (ClassNotFoundException e) {
                    // handle exception
                } catch (InstantiationException e) {
                    // handle exception
                } catch (IllegalAccessException e) {
                    // handle exception
                }
                new MainInterface().setVisible(true);
            }
        });
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boutonsCouleur = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenuItem1.setText("Dosage d'une monobase forte par un monoacide fort");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("Item");
        jPopupMenu1.add(jMenuItem2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FITEX 2.0");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    
    
    
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup boutonsCouleur;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void openDatas() {
        dataTable.setVisible(true);
    }

    @Override
    public void setParam(boolean autoScale, double xmin, double xmax, double deltaX, double ymin, double ymax, double deltaY) {
        
    }

    @Override
    public void setAutoScale(boolean autoScale) {
        
    }

    @Override
    public void setFunctionModel(String function, Color color) {
        
    }
    
}
