// This class was generated by 172 StubGenerator.
// Contents subject to change without notice.
// @generated

package eu.scy.mobile.toolbroker.demo.client;

public interface RepositoryService extends java.rmi.Remote {
	public String saveELO(MobileELO arg0) throws java.rmi.RemoteException;

	public MobileELO getELO(int arg0) throws java.rmi.RemoteException;

}
