/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package eu.scy.client.desktop.scydesktop.tools.mission.springimport;

/**
 *
 * @author SikkenJ
 */
public enum EloFunctionalRole
{

   MAP_CONCEPT, MAP_INITIAL_IDEAS, MAP_KEY_IDEAS,
   DATASET_MANUAL, DATASET_AUTOMATIC, DATASET_PROCESSED,
   EXPERIMENTAL_DESIGN, EXPERIMENTAL_CONCLUSION,
   DRAWING_DESIGN,
   HYPOTHESIS,
   RESEARCH_QUESTION,
   INTERVIEW,
   DOCUMENT_DESIGN,
   REPORT_EVALUATION, REPORT_FINAL,
   PRESENTATION_DESIGN, PRESENTATION_FINAL, PRESENTATION_EXPERT,
   DOCUMENT_REFLECTION,
   INFORMATION_RESOURCE, INFORMATION_ASSIGNMENT, INFORMATION_HELP,
   SOURCE_DATA
}
