/*
 * PrintDialog.java
 *
 * Created on 31 juillet 2008, 16:24
 */

package eu.scy.tools.copex.print;

import eu.scy.tools.copex.edp.EdPPanel;
import eu.scy.tools.copex.utilities.CopexUtilities;
import javax.swing.*;


/**
 * fenetre de dialogue qui permet de choisir les parametres d'impression
 * @author  MBO
 */
public class PrintDialog extends JDialog {

    
    // ATTRIBUTS
    /* fenetre mere */
    private EdPPanel edP;
    /* impression du proc*/
    private boolean printProc;
    /* impression desc commentaires */
    private boolean printComments;
    /* impression de la feuille de donnees */
    private boolean printDataSheet;
    
    
    
    // CONSTRUCTEUR 
    /** Creates new form PrintDialog */
    public PrintDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public PrintDialog(EdPPanel edP) {
        super();
        this.edP = edP;
        setLocationRelativeTo(edP);  
        initComponents();
        setModal(true);
        resizeComponents();
    }

    private void resizeComponents(){
        // label print
       this.labelPrint.setSize(CopexUtilities.lenghtOfString(this.labelPrint.getText(), getFontMetrics(this.labelPrint.getFont())), this.labelPrint.getHeight());
       // cb proc
       this.cbProc.setSize(CopexUtilities.lenghtOfString(this.cbProc.getText(), getFontMetrics(this.cbProc.getFont())), this.cbProc.getHeight());
       // cb comments
       this.cbComments.setSize(CopexUtilities.lenghtOfString(this.cbComments.getText(), getFontMetrics(this.cbComments.getFont())), this.cbComments.getHeight());
       // cb datasheet
       this.cbDataSheet.setSize(CopexUtilities.lenghtOfString(this.cbDataSheet.getText(), getFontMetrics(this.cbDataSheet.getFont())), this.cbDataSheet.getHeight());
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonOk = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        labelPrint = new javax.swing.JLabel();
        cbProc = new javax.swing.JCheckBox();
        cbComments = new javax.swing.JCheckBox();
        cbDataSheet = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle(edP.getBundleString("TITLE_DIALOG_PRINT"));
        setModal(true);
        setResizable(false);

        buttonOk.setText(edP.getBundleString("BUTTON_OK"));
        buttonOk.setName("buttonOk"); // NOI18N
        buttonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOkActionPerformed(evt);
            }
        });

        buttonCancel.setText(edP.getBundleString("BUTTON_CANCEL"));
        buttonCancel.setName("buttonCancel"); // NOI18N
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        labelPrint.setFont(new java.awt.Font("Tahoma", 1, 11));
        labelPrint.setText(edP.getBundleString("LABEL_PRINT")+" :");
        labelPrint.setName("labelPrint"); // NOI18N

        cbProc.setFont(new java.awt.Font("Tahoma", 1, 11));
        cbProc.setSelected(true);
        cbProc.setText(edP.getBundleString("LABEL_PROC_ACTIV"));
        cbProc.setName("cbProc"); // NOI18N
        cbProc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProcActionPerformed(evt);
            }
        });

        cbComments.setFont(new java.awt.Font("Tahoma", 1, 11));
        cbComments.setSelected(true);
        cbComments.setText(edP.getBundleString("LABEL_COMMENTS_PROC"));
        cbComments.setName("cbComments"); // NOI18N

        cbDataSheet.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cbDataSheet.setText(edP.getBundleString("LABEL_PRINT_DATASHEET"));
        cbDataSheet.setEnabled(false);
        cbDataSheet.setName("cbDataSheet"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelPrint))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(cbComments))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbDataSheet)
                            .addComponent(cbProc)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(buttonOk)
                        .addGap(69, 69, 69)
                        .addComponent(buttonCancel)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPrint)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbProc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbComments)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbDataSheet)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonOk, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCancel))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void buttonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOkActionPerformed
    // recuperation des donnees
    printProc = cbProc.isSelected();
    // comments
    printComments = cbComments.isSelected();
    // datasheet
    printDataSheet = cbDataSheet.isSelected();
    edP.printCopex(printProc, printComments, printDataSheet);
   
    this.dispose();
}//GEN-LAST:event_buttonOkActionPerformed

private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
    this.dispose();
}//GEN-LAST:event_buttonCancelActionPerformed

private void cbProcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProcActionPerformed
    cbComments.setEnabled(cbProc.isSelected());
}//GEN-LAST:event_cbProcActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PrintDialog dialog = new PrintDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonOk;
    private javax.swing.JCheckBox cbComments;
    private javax.swing.JCheckBox cbDataSheet;
    private javax.swing.JCheckBox cbProc;
    private javax.swing.JLabel labelPrint;
    // End of variables declaration//GEN-END:variables

}
